// Code generated by protoc-gen-go. DO NOT EDIT.
// source: collection.proto

package collection

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Coordinate struct {
	Lon                  float32  `protobuf:"fixed32,1,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat                  float32  `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{0}
}

func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (m *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(m, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *Coordinate) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

type Picture struct {
	Src                  string   `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Picture) Reset()         { *m = Picture{} }
func (m *Picture) String() string { return proto.CompactTextString(m) }
func (*Picture) ProtoMessage()    {}
func (*Picture) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{1}
}

func (m *Picture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Picture.Unmarshal(m, b)
}
func (m *Picture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Picture.Marshal(b, m, deterministic)
}
func (m *Picture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Picture.Merge(m, src)
}
func (m *Picture) XXX_Size() int {
	return xxx_messageInfo_Picture.Size(m)
}
func (m *Picture) XXX_DiscardUnknown() {
	xxx_messageInfo_Picture.DiscardUnknown(m)
}

var xxx_messageInfo_Picture proto.InternalMessageInfo

func (m *Picture) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

type Product struct {
	// @inject_tag: id:"ip"
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price                int32    `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Like                 int32    `protobuf:"varint,5,opt,name=like,proto3" json:"like,omitempty"`
	Recipes              []string `protobuf:"bytes,6,rep,name=recipes,proto3" json:"recipes,omitempty"`
	Notation             int32    `protobuf:"varint,7,opt,name=notation,proto3" json:"notation,omitempty"`
	Discount             int32    `protobuf:"varint,8,opt,name=discount,proto3" json:"discount,omitempty"`
	Picture              string   `protobuf:"bytes,9,opt,name=picture,proto3" json:"picture,omitempty"`
	Size                 string   `protobuf:"bytes,10,opt,name=size,proto3" json:"size,omitempty"`
	Position             int32    `protobuf:"varint,11,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{2}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetLike() int32 {
	if m != nil {
		return m.Like
	}
	return 0
}

func (m *Product) GetRecipes() []string {
	if m != nil {
		return m.Recipes
	}
	return nil
}

func (m *Product) GetNotation() int32 {
	if m != nil {
		return m.Notation
	}
	return 0
}

func (m *Product) GetDiscount() int32 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *Product) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *Product) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *Product) GetPosition() int32 {
	if m != nil {
		return m.Position
	}
	return 0
}

type Collection struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Categorycode         string     `protobuf:"bytes,3,opt,name=categorycode,proto3" json:"categorycode,omitempty"`
	Categoryname         string     `protobuf:"bytes,4,opt,name=categoryname,proto3" json:"categoryname,omitempty"`
	Placeid              string     `protobuf:"bytes,5,opt,name=placeid,proto3" json:"placeid,omitempty"`
	Products             []*Product `protobuf:"bytes,6,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Collection) Reset()         { *m = Collection{} }
func (m *Collection) String() string { return proto.CompactTextString(m) }
func (*Collection) ProtoMessage()    {}
func (*Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{3}
}

func (m *Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collection.Unmarshal(m, b)
}
func (m *Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collection.Marshal(b, m, deterministic)
}
func (m *Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collection.Merge(m, src)
}
func (m *Collection) XXX_Size() int {
	return xxx_messageInfo_Collection.Size(m)
}
func (m *Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_Collection.DiscardUnknown(m)
}

var xxx_messageInfo_Collection proto.InternalMessageInfo

func (m *Collection) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Collection) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Collection) GetCategorycode() string {
	if m != nil {
		return m.Categorycode
	}
	return ""
}

func (m *Collection) GetCategoryname() string {
	if m != nil {
		return m.Categoryname
	}
	return ""
}

func (m *Collection) GetPlaceid() string {
	if m != nil {
		return m.Placeid
	}
	return ""
}

func (m *Collection) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type Gastronomie struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gastronomie) Reset()         { *m = Gastronomie{} }
func (m *Gastronomie) String() string { return proto.CompactTextString(m) }
func (*Gastronomie) ProtoMessage()    {}
func (*Gastronomie) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{4}
}

func (m *Gastronomie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gastronomie.Unmarshal(m, b)
}
func (m *Gastronomie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gastronomie.Marshal(b, m, deterministic)
}
func (m *Gastronomie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gastronomie.Merge(m, src)
}
func (m *Gastronomie) XXX_Size() int {
	return xxx_messageInfo_Gastronomie.Size(m)
}
func (m *Gastronomie) XXX_DiscardUnknown() {
	xxx_messageInfo_Gastronomie.DiscardUnknown(m)
}

var xxx_messageInfo_Gastronomie proto.InternalMessageInfo

func (m *Gastronomie) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateCollectionRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCollectionRequest) Reset()         { *m = CreateCollectionRequest{} }
func (m *CreateCollectionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCollectionRequest) ProtoMessage()    {}
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{5}
}

func (m *CreateCollectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCollectionRequest.Unmarshal(m, b)
}
func (m *CreateCollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCollectionRequest.Marshal(b, m, deterministic)
}
func (m *CreateCollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCollectionRequest.Merge(m, src)
}
func (m *CreateCollectionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCollectionRequest.Size(m)
}
func (m *CreateCollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCollectionRequest proto.InternalMessageInfo

func (m *CreateCollectionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{6}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{7}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DeleteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DeleteResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateRequest struct {
	Payload              *Collection `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{8}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetPayload() *Collection {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateRequest struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload              *Collection `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{9}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetPayload() *Collection {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{10}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UpdateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DetailResponse struct {
	Status               int32       `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *Collection `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DetailResponse) Reset()         { *m = DetailResponse{} }
func (m *DetailResponse) String() string { return proto.CompactTextString(m) }
func (*DetailResponse) ProtoMessage()    {}
func (*DetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{11}
}

func (m *DetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailResponse.Unmarshal(m, b)
}
func (m *DetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailResponse.Marshal(b, m, deterministic)
}
func (m *DetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailResponse.Merge(m, src)
}
func (m *DetailResponse) XXX_Size() int {
	return xxx_messageInfo_DetailResponse.Size(m)
}
func (m *DetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetailResponse proto.InternalMessageInfo

func (m *DetailResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DetailResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DetailResponse) GetData() *Collection {
	if m != nil {
		return m.Data
	}
	return nil
}

type SearchRequest struct {
	Q                    string   `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	From                 int32    `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   int32    `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{12}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *SearchRequest) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *SearchRequest) GetTo() int32 {
	if m != nil {
		return m.To
	}
	return 0
}

type ListResponse struct {
	Status               int32         `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Total                int64         `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*Collection `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{13}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ListResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListResponse) GetData() []*Collection {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{14}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type FoodCategory struct {
	Categoryname         string   `protobuf:"bytes,1,opt,name=categoryname,proto3" json:"categoryname,omitempty"`
	Categorycode         string   `protobuf:"bytes,2,opt,name=categorycode,proto3" json:"categorycode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FoodCategory) Reset()         { *m = FoodCategory{} }
func (m *FoodCategory) String() string { return proto.CompactTextString(m) }
func (*FoodCategory) ProtoMessage()    {}
func (*FoodCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{15}
}

func (m *FoodCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodCategory.Unmarshal(m, b)
}
func (m *FoodCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodCategory.Marshal(b, m, deterministic)
}
func (m *FoodCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodCategory.Merge(m, src)
}
func (m *FoodCategory) XXX_Size() int {
	return xxx_messageInfo_FoodCategory.Size(m)
}
func (m *FoodCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodCategory.DiscardUnknown(m)
}

var xxx_messageInfo_FoodCategory proto.InternalMessageInfo

func (m *FoodCategory) GetCategoryname() string {
	if m != nil {
		return m.Categoryname
	}
	return ""
}

func (m *FoodCategory) GetCategorycode() string {
	if m != nil {
		return m.Categorycode
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{16}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Coordinate)(nil), "collection.Coordinate")
	proto.RegisterType((*Picture)(nil), "collection.Picture")
	proto.RegisterType((*Product)(nil), "collection.Product")
	proto.RegisterType((*Collection)(nil), "collection.Collection")
	proto.RegisterType((*Gastronomie)(nil), "collection.Gastronomie")
	proto.RegisterType((*CreateCollectionRequest)(nil), "collection.CreateCollectionRequest")
	proto.RegisterType((*ID)(nil), "collection.ID")
	proto.RegisterType((*DeleteResponse)(nil), "collection.DeleteResponse")
	proto.RegisterType((*CreateRequest)(nil), "collection.CreateRequest")
	proto.RegisterType((*UpdateRequest)(nil), "collection.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "collection.UpdateResponse")
	proto.RegisterType((*DetailResponse)(nil), "collection.DetailResponse")
	proto.RegisterType((*SearchRequest)(nil), "collection.SearchRequest")
	proto.RegisterType((*ListResponse)(nil), "collection.ListResponse")
	proto.RegisterType((*CreateResponse)(nil), "collection.CreateResponse")
	proto.RegisterType((*FoodCategory)(nil), "collection.FoodCategory")
	proto.RegisterType((*Empty)(nil), "collection.Empty")
}

func init() { proto.RegisterFile("collection.proto", fileDescriptor_9eceb2b1ad103104) }

var fileDescriptor_9eceb2b1ad103104 = []byte{
	// 683 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x41, 0x6f, 0xd3, 0x4a,
	0x10, 0x96, 0xed, 0x38, 0x6e, 0x26, 0x69, 0xd4, 0xee, 0xab, 0xfa, 0xfc, 0xf2, 0x2e, 0xc5, 0xa7,
	0x0a, 0x89, 0x52, 0x0a, 0xe2, 0x84, 0x84, 0x4a, 0x0b, 0x55, 0x25, 0x54, 0x15, 0x57, 0x70, 0xe0,
	0xb6, 0xd8, 0x03, 0x2c, 0x38, 0x5e, 0x77, 0x3d, 0x41, 0x0a, 0x07, 0xae, 0xfc, 0x20, 0x7e, 0x02,
	0x7f, 0x0c, 0xed, 0xae, 0x9d, 0xac, 0xd3, 0xa2, 0xa2, 0x8a, 0xdb, 0xcc, 0x78, 0xf6, 0xf3, 0xf7,
	0x7d, 0x3b, 0x63, 0xc3, 0x46, 0x26, 0x8b, 0x02, 0x33, 0x12, 0xb2, 0xdc, 0xab, 0x94, 0x24, 0xc9,
	0x60, 0x59, 0x49, 0xf6, 0x01, 0x8e, 0xa4, 0x54, 0xb9, 0x28, 0x39, 0x21, 0xdb, 0x80, 0xa0, 0x90,
	0x65, 0xec, 0xed, 0x78, 0xbb, 0x7e, 0xaa, 0x43, 0x53, 0xe1, 0x14, 0xfb, 0x4d, 0x85, 0x53, 0xf2,
	0x3f, 0x44, 0xe7, 0x22, 0xa3, 0x99, 0x32, 0xed, 0xb5, 0xca, 0x4c, 0xfb, 0x20, 0xd5, 0x61, 0xf2,
	0xdd, 0x87, 0xe8, 0x5c, 0xc9, 0x7c, 0x96, 0x11, 0x1b, 0x83, 0x2f, 0xf2, 0xe6, 0xa1, 0x2f, 0x72,
	0xc6, 0xa0, 0x47, 0xf3, 0x0a, 0x0d, 0xd6, 0x20, 0x35, 0xb1, 0xae, 0x95, 0x7c, 0x8a, 0x71, 0x60,
	0x6b, 0x3a, 0x66, 0x5b, 0x10, 0x56, 0x4a, 0x64, 0x18, 0xf7, 0x76, 0xbc, 0xdd, 0x30, 0xb5, 0x89,
	0xee, 0x2c, 0xc4, 0x67, 0x8c, 0x43, 0x53, 0x34, 0x31, 0x8b, 0x21, 0x52, 0x98, 0x89, 0x0a, 0xeb,
	0xb8, 0xbf, 0x13, 0xec, 0x0e, 0xd2, 0x36, 0x65, 0x13, 0x58, 0x2b, 0x25, 0x71, 0x2d, 0x31, 0x8e,
	0xcc, 0x89, 0x45, 0xae, 0x9f, 0xe5, 0xa2, 0xce, 0xe4, 0xac, 0xa4, 0x78, 0xcd, 0x3e, 0x6b, 0x73,
	0x8d, 0x58, 0x59, 0x71, 0xf1, 0xc0, 0x50, 0x6a, 0x53, 0xfd, 0xfe, 0x5a, 0x7c, 0xc5, 0x18, 0x2c,
	0x53, 0x1d, 0x6b, 0xa4, 0x4a, 0xd6, 0xc2, 0xbc, 0x65, 0x68, 0x91, 0xda, 0x3c, 0xf9, 0xe9, 0x69,
	0x67, 0x5b, 0x9f, 0xaf, 0x33, 0xc3, 0x08, 0xf7, 0x1d, 0xe1, 0x09, 0x8c, 0x32, 0x4e, 0xf8, 0x41,
	0xaa, 0x79, 0x26, 0xf3, 0xd6, 0x94, 0x4e, 0xcd, 0xed, 0x31, 0xe7, 0x7b, 0xdd, 0x1e, 0x83, 0xa3,
	0x45, 0x14, 0x3c, 0x43, 0x91, 0x1b, 0xb7, 0xb4, 0x08, 0x9b, 0xb2, 0xfb, 0xb0, 0x56, 0xd9, 0xdb,
	0xb1, 0x8e, 0x0d, 0x0f, 0xfe, 0xd9, 0x73, 0xc6, 0xa3, 0xb9, 0xb9, 0x74, 0xd1, 0x94, 0xdc, 0x81,
	0xe1, 0x09, 0xaf, 0x49, 0xc9, 0x52, 0x4e, 0xc5, 0xf2, 0xba, 0xbc, 0x25, 0xeb, 0xe4, 0x1e, 0xfc,
	0x7b, 0xa4, 0x90, 0x13, 0x2e, 0xd5, 0xa6, 0x78, 0x39, 0xc3, 0x9a, 0xae, 0x6d, 0xdf, 0x02, 0xff,
	0xf4, 0x78, 0xd5, 0x8e, 0xe4, 0x0c, 0xc6, 0xc7, 0x58, 0x20, 0x61, 0x8a, 0x75, 0x25, 0xcb, 0x1a,
	0xd9, 0x36, 0xf4, 0x6b, 0xe2, 0x34, 0xab, 0x4d, 0x57, 0x98, 0x36, 0x99, 0x9e, 0x0e, 0x54, 0x4a,
	0xaa, 0xc6, 0x39, 0x9b, 0x34, 0x78, 0xc1, 0x02, 0xef, 0x10, 0xd6, 0x2d, 0xa9, 0x96, 0xca, 0x3e,
	0x44, 0x15, 0x9f, 0x17, 0x92, 0xdb, 0xb7, 0x0e, 0x0f, 0xb6, 0x5d, 0xe1, 0x0e, 0xf5, 0xb6, 0x2d,
	0x79, 0x05, 0xeb, 0xaf, 0xab, 0xdc, 0x81, 0x58, 0xbd, 0x42, 0x07, 0xd2, 0xff, 0x33, 0xc8, 0x33,
	0x18, 0xb7, 0x90, 0x7f, 0x45, 0xe5, 0x27, 0xed, 0x1a, 0x71, 0x51, 0xdc, 0x12, 0xef, 0x2e, 0xf4,
	0x72, 0x4e, 0xdc, 0x0c, 0xd1, 0xef, 0xe9, 0x9b, 0x1e, 0xed, 0xe8, 0x05, 0x72, 0x95, 0x7d, 0x6c,
	0xed, 0x18, 0x81, 0x77, 0xd9, 0xb8, 0xe1, 0x5d, 0xea, 0xab, 0x7e, 0xaf, 0xe4, 0xd4, 0xe0, 0x87,
	0xa9, 0x89, 0x35, 0x5d, 0x92, 0x86, 0x6e, 0x98, 0xfa, 0x24, 0x93, 0x6f, 0x30, 0x7a, 0x29, 0x6a,
	0xba, 0x25, 0xd9, 0x2d, 0x08, 0x49, 0x12, 0x2f, 0x0c, 0x60, 0x90, 0xda, 0xc4, 0x91, 0x10, 0xdc,
	0x28, 0xe1, 0x0c, 0xc6, 0xed, 0x50, 0xdc, 0xc0, 0xc0, 0x1a, 0xed, 0x2f, 0xae, 0x7a, 0xc1, 0x28,
	0x70, 0x18, 0x25, 0x6f, 0x60, 0xf4, 0x42, 0xca, 0xfc, 0xa8, 0xd9, 0xbd, 0x2b, 0xbb, 0xe9, 0x5d,
	0xb3, 0x9b, 0xab, 0x3b, 0xee, 0x5f, 0xdd, 0xf1, 0x24, 0x82, 0xf0, 0xf9, 0xb4, 0xa2, 0xf9, 0xc1,
	0x0f, 0x1f, 0x36, 0x97, 0x2a, 0x2e, 0x50, 0x7d, 0xd1, 0x5f, 0xc2, 0xc7, 0x10, 0x9d, 0x20, 0x69,
	0x27, 0xd9, 0xa6, 0xab, 0xd7, 0x9c, 0x99, 0xc4, 0x6e, 0xa9, 0x63, 0xf7, 0x03, 0x08, 0x4e, 0x90,
	0xd8, 0xd8, 0x6d, 0x38, 0x3d, 0x9e, 0x4c, 0xdc, 0x7c, 0x65, 0x9c, 0x9e, 0x40, 0x70, 0x98, 0xe7,
	0xec, 0xbf, 0x8e, 0xad, 0xee, 0x5e, 0x75, 0x4f, 0xaf, 0xb8, 0xfb, 0x14, 0xfa, 0x76, 0xdc, 0xbb,
	0x00, 0x9d, 0xad, 0xea, 0x02, 0xac, 0x6c, 0xc7, 0x23, 0xe8, 0xdb, 0xaf, 0xc2, 0x4d, 0xa4, 0xdd,
	0x2f, 0xc7, 0xb3, 0xd1, 0x5b, 0xe7, 0x07, 0xf7, 0xae, 0x6f, 0xfe, 0x79, 0x0f, 0x7f, 0x05, 0x00,
	0x00, 0xff, 0xff, 0x88, 0x14, 0x8c, 0x56, 0x07, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CollectionServiceClient is the client API for CollectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CollectionServiceClient interface {
	GetList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListResponse, error)
	Get(ctx context.Context, in *ID, opts ...grpc.CallOption) (*DetailResponse, error)
	Add(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *ID, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type collectionServiceClient struct {
	cc *grpc.ClientConn
}

func NewCollectionServiceClient(cc *grpc.ClientConn) CollectionServiceClient {
	return &collectionServiceClient{cc}
}

func (c *collectionServiceClient) GetList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/collection.CollectionService/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionServiceClient) Get(ctx context.Context, in *ID, opts ...grpc.CallOption) (*DetailResponse, error) {
	out := new(DetailResponse)
	err := c.cc.Invoke(ctx, "/collection.CollectionService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionServiceClient) Add(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/collection.CollectionService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/collection.CollectionService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionServiceClient) Delete(ctx context.Context, in *ID, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/collection.CollectionService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectionServiceServer is the server API for CollectionService service.
type CollectionServiceServer interface {
	GetList(context.Context, *Empty) (*ListResponse, error)
	Get(context.Context, *ID) (*DetailResponse, error)
	Add(context.Context, *CreateRequest) (*CreateResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Delete(context.Context, *ID) (*DeleteResponse, error)
}

// UnimplementedCollectionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCollectionServiceServer struct {
}

func (*UnimplementedCollectionServiceServer) GetList(ctx context.Context, req *Empty) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (*UnimplementedCollectionServiceServer) Get(ctx context.Context, req *ID) (*DetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedCollectionServiceServer) Add(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedCollectionServiceServer) Update(ctx context.Context, req *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedCollectionServiceServer) Delete(ctx context.Context, req *ID) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterCollectionServiceServer(s *grpc.Server, srv CollectionServiceServer) {
	s.RegisterService(&_CollectionService_serviceDesc, srv)
}

func _CollectionService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/collection.CollectionService/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServiceServer).GetList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/collection.CollectionService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServiceServer).Get(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/collection.CollectionService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServiceServer).Add(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/collection.CollectionService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/collection.CollectionService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServiceServer).Delete(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

var _CollectionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "collection.CollectionService",
	HandlerType: (*CollectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _CollectionService_GetList_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CollectionService_Get_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _CollectionService_Add_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CollectionService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CollectionService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "collection.proto",
}
