version: '3'

services:
  search-engine:
    hostname: search-engine
    build: ./search-engine
    entrypoint: /usr/src/app/startdev.sh
    volumes: 
      - ./search-engine/src:/usr/src/app/src:ro
    ports: 
      - 9500:5500
    networks: 
      - dkrv-network
    env_file:
      - ./dkrv.env
    depends_on:
      - elasticsearch_primary
  dkrv-place:
    hostname: dkrv-place
    build: ./dkrv-place
    ports: 
      - 5200:5200
      - 5300:5300
      - 5400:5400
    networks: 
      - dkrv-network
    env_file:
      - ./dkrv.env
  dkrv-core:
    hostname: dkrv-core
    build: ./dkrv-core
    entrypoint: /usr/src/app/startdev.sh
    volumes:
      - ./dkrv-core/src:/usr/src/app/src:ro
    ports: 
      - 5000:5000
    networks: 
      - dkrv-network
    env_file:
      - ./dkrv.env
    depends_on:
      - search-engine
  elasticsearch_primary:
    hostname: elasticsearch_primary
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    container_name: elasticsearch_primary
    environment:
      - node.name=elasticsearch_primary
      - cluster.initial_master_nodes=elasticsearch_primary
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_primary_data:/usr/share/elasticsearch/data
    ports:
      - 7200:9200
    networks:
      - dkrv-network

volumes:
  elasticsearch_primary_data:
    driver: local
  esdata02:
    driver: local

networks:
  dkrv-network: {}