version: '3'

services:
  search-engine:
    hostname: search-engine
    build:
      context: ./search-engine
      dockerfile: ./search-engine/Dockerfile.dev
    volumes: 
      - ./search-engine/src:/usr/src/app/src:ro
      - ./search-engine/dist:/usr/src/app/dist
    working_dir: /usr/src/app
    ports: 
      - 9500:5000
    networks: 
      - dkrv-network
    env_file:
      - ./dkrv.env
    depends_on:
      - elasticsearch_primary
  elasticsearch_primary:
    hostname: elasticsearch_primary
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    container_name: elasticsearch_primary
    environment:
      - node.name=elasticsearch_primary
      - cluster.initial_master_nodes=elasticsearch_primary
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_primary_data:/usr/share/elasticsearch/data
    ports:
      - '7200:9200'
    networks:
      - dkrv-network

volumes:
  elasticsearch_primary_data:
    driver: local
  esdata02:
    driver: local

networks:
  dkrv-network: {}