// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package event

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestEmpty) Reset()         { *m = RequestEmpty{} }
func (m *RequestEmpty) String() string { return proto.CompactTextString(m) }
func (*RequestEmpty) ProtoMessage()    {}
func (*RequestEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *RequestEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestEmpty.Unmarshal(m, b)
}
func (m *RequestEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestEmpty.Marshal(b, m, deterministic)
}
func (m *RequestEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestEmpty.Merge(m, src)
}
func (m *RequestEmpty) XXX_Size() int {
	return xxx_messageInfo_RequestEmpty.Size(m)
}
func (m *RequestEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_RequestEmpty proto.InternalMessageInfo

type Picture struct {
	Src                  string   `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Picture) Reset()         { *m = Picture{} }
func (m *Picture) String() string { return proto.CompactTextString(m) }
func (*Picture) ProtoMessage()    {}
func (*Picture) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *Picture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Picture.Unmarshal(m, b)
}
func (m *Picture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Picture.Marshal(b, m, deterministic)
}
func (m *Picture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Picture.Merge(m, src)
}
func (m *Picture) XXX_Size() int {
	return xxx_messageInfo_Picture.Size(m)
}
func (m *Picture) XXX_DiscardUnknown() {
	xxx_messageInfo_Picture.DiscardUnknown(m)
}

var xxx_messageInfo_Picture proto.InternalMessageInfo

func (m *Picture) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

type Gallery struct {
	Main                 int32      `protobuf:"varint,1,opt,name=main,proto3" json:"main,omitempty"`
	Pictures             []*Picture `protobuf:"bytes,2,rep,name=pictures,proto3" json:"pictures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Gallery) Reset()         { *m = Gallery{} }
func (m *Gallery) String() string { return proto.CompactTextString(m) }
func (*Gallery) ProtoMessage()    {}
func (*Gallery) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{2}
}

func (m *Gallery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gallery.Unmarshal(m, b)
}
func (m *Gallery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gallery.Marshal(b, m, deterministic)
}
func (m *Gallery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gallery.Merge(m, src)
}
func (m *Gallery) XXX_Size() int {
	return xxx_messageInfo_Gallery.Size(m)
}
func (m *Gallery) XXX_DiscardUnknown() {
	xxx_messageInfo_Gallery.DiscardUnknown(m)
}

var xxx_messageInfo_Gallery proto.InternalMessageInfo

func (m *Gallery) GetMain() int32 {
	if m != nil {
		return m.Main
	}
	return 0
}

func (m *Gallery) GetPictures() []*Picture {
	if m != nil {
		return m.Pictures
	}
	return nil
}

type Category struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{3}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Coordinate struct {
	Lon                  float32  `protobuf:"fixed32,1,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat                  float32  `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{4}
}

func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (m *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(m, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *Coordinate) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

type Price struct {
	Base                 int64    `protobuf:"varint,1,opt,name=base,proto3" json:"base,omitempty"`
	Currency             string   `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Price) Reset()         { *m = Price{} }
func (m *Price) String() string { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()    {}
func (*Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{5}
}

func (m *Price) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Price.Unmarshal(m, b)
}
func (m *Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Price.Marshal(b, m, deterministic)
}
func (m *Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Price.Merge(m, src)
}
func (m *Price) XXX_Size() int {
	return xxx_messageInfo_Price.Size(m)
}
func (m *Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Price proto.InternalMessageInfo

func (m *Price) GetBase() int64 {
	if m != nil {
		return m.Base
	}
	return 0
}

func (m *Price) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type Host struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Src                  string   `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Host) Reset()         { *m = Host{} }
func (m *Host) String() string { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()    {}
func (*Host) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{6}
}

func (m *Host) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Host.Unmarshal(m, b)
}
func (m *Host) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Host.Marshal(b, m, deterministic)
}
func (m *Host) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Host.Merge(m, src)
}
func (m *Host) XXX_Size() int {
	return xxx_messageInfo_Host.Size(m)
}
func (m *Host) XXX_DiscardUnknown() {
	xxx_messageInfo_Host.DiscardUnknown(m)
}

var xxx_messageInfo_Host proto.InternalMessageInfo

func (m *Host) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Host) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

type Location struct {
	Address              string      `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Cpc                  string      `protobuf:"bytes,2,opt,name=cpc,proto3" json:"cpc,omitempty"`
	Zone                 string      `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	Coordinate           *Coordinate `protobuf:"bytes,4,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{7}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Location) GetCpc() string {
	if m != nil {
		return m.Cpc
	}
	return ""
}

func (m *Location) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *Location) GetCoordinate() *Coordinate {
	if m != nil {
		return m.Coordinate
	}
	return nil
}

type Event struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Placeid              string    `protobuf:"bytes,3,opt,name=placeid,proto3" json:"placeid,omitempty"`
	Phone                string    `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string    `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Place                string    `protobuf:"bytes,6,opt,name=place,proto3" json:"place,omitempty"`
	Date                 string    `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	Categories           *Category `protobuf:"bytes,8,opt,name=categories,proto3" json:"categories,omitempty"`
	Description          string    `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Price                *Price    `protobuf:"bytes,10,opt,name=price,proto3" json:"price,omitempty"`
	Location             *Location `protobuf:"bytes,11,opt,name=location,proto3" json:"location,omitempty"`
	Nbplace              int64     `protobuf:"varint,12,opt,name=nbplace,proto3" json:"nbplace,omitempty"`
	Likes                int64     `protobuf:"varint,13,opt,name=likes,proto3" json:"likes,omitempty"`
	Gallery              *Gallery  `protobuf:"bytes,14,opt,name=gallery,proto3" json:"gallery,omitempty"`
	Hosts                []*Host   `protobuf:"bytes,15,rep,name=hosts,proto3" json:"hosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{8}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event) GetPlaceid() string {
	if m != nil {
		return m.Placeid
	}
	return ""
}

func (m *Event) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Event) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Event) GetPlace() string {
	if m != nil {
		return m.Place
	}
	return ""
}

func (m *Event) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Event) GetCategories() *Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetPrice() *Price {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *Event) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Event) GetNbplace() int64 {
	if m != nil {
		return m.Nbplace
	}
	return 0
}

func (m *Event) GetLikes() int64 {
	if m != nil {
		return m.Likes
	}
	return 0
}

func (m *Event) GetGallery() *Gallery {
	if m != nil {
		return m.Gallery
	}
	return nil
}

func (m *Event) GetHosts() []*Host {
	if m != nil {
		return m.Hosts
	}
	return nil
}

type ListResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Total                int64    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Payload              []*Event `protobuf:"bytes,4,rep,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{9}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ListResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListResponse) GetPayload() []*Event {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateRequest struct {
	Payload              *Event   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{10}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetPayload() *Event {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Payload              string   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{11}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateResponse) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type DetailRequest struct {
	Id                   string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailRequest) Reset()         { *m = DetailRequest{} }
func (m *DetailRequest) String() string { return proto.CompactTextString(m) }
func (*DetailRequest) ProtoMessage()    {}
func (*DetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{12}
}

func (m *DetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailRequest.Unmarshal(m, b)
}
func (m *DetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailRequest.Marshal(b, m, deterministic)
}
func (m *DetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailRequest.Merge(m, src)
}
func (m *DetailRequest) XXX_Size() int {
	return xxx_messageInfo_DetailRequest.Size(m)
}
func (m *DetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetailRequest proto.InternalMessageInfo

func (m *DetailRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DetailResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Payload              *Event   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailResponse) Reset()         { *m = DetailResponse{} }
func (m *DetailResponse) String() string { return proto.CompactTextString(m) }
func (*DetailResponse) ProtoMessage()    {}
func (*DetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{13}
}

func (m *DetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailResponse.Unmarshal(m, b)
}
func (m *DetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailResponse.Marshal(b, m, deterministic)
}
func (m *DetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailResponse.Merge(m, src)
}
func (m *DetailResponse) XXX_Size() int {
	return xxx_messageInfo_DetailResponse.Size(m)
}
func (m *DetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetailResponse proto.InternalMessageInfo

func (m *DetailResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DetailResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DetailResponse) GetPayload() *Event {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload              *Event   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{14}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetPayload() *Event {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Payload              *Event   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{15}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UpdateResponse) GetPayload() *Event {
	if m != nil {
		return m.Payload
	}
	return nil
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{16}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Payload              bool     `protobuf:"varint,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{17}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DeleteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DeleteResponse) GetPayload() bool {
	if m != nil {
		return m.Payload
	}
	return false
}

type SearchRequest struct {
	Payload              *SearchParams `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{18}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetPayload() *SearchParams {
	if m != nil {
		return m.Payload
	}
	return nil
}

type SearchParams struct {
	Q                    string   `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	From                 int32    `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   int32    `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	Fromdate             string   `protobuf:"bytes,4,opt,name=fromdate,proto3" json:"fromdate,omitempty"`
	Todate               string   `protobuf:"bytes,5,opt,name=todate,proto3" json:"todate,omitempty"`
	Category             []string `protobuf:"bytes,6,rep,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchParams) Reset()         { *m = SearchParams{} }
func (m *SearchParams) String() string { return proto.CompactTextString(m) }
func (*SearchParams) ProtoMessage()    {}
func (*SearchParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{19}
}

func (m *SearchParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchParams.Unmarshal(m, b)
}
func (m *SearchParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchParams.Marshal(b, m, deterministic)
}
func (m *SearchParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchParams.Merge(m, src)
}
func (m *SearchParams) XXX_Size() int {
	return xxx_messageInfo_SearchParams.Size(m)
}
func (m *SearchParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchParams.DiscardUnknown(m)
}

var xxx_messageInfo_SearchParams proto.InternalMessageInfo

func (m *SearchParams) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *SearchParams) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *SearchParams) GetTo() int32 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *SearchParams) GetFromdate() string {
	if m != nil {
		return m.Fromdate
	}
	return ""
}

func (m *SearchParams) GetTodate() string {
	if m != nil {
		return m.Todate
	}
	return ""
}

func (m *SearchParams) GetCategory() []string {
	if m != nil {
		return m.Category
	}
	return nil
}

func init() {
	proto.RegisterType((*RequestEmpty)(nil), "event.RequestEmpty")
	proto.RegisterType((*Picture)(nil), "event.Picture")
	proto.RegisterType((*Gallery)(nil), "event.Gallery")
	proto.RegisterType((*Category)(nil), "event.Category")
	proto.RegisterType((*Coordinate)(nil), "event.Coordinate")
	proto.RegisterType((*Price)(nil), "event.Price")
	proto.RegisterType((*Host)(nil), "event.Host")
	proto.RegisterType((*Location)(nil), "event.Location")
	proto.RegisterType((*Event)(nil), "event.Event")
	proto.RegisterType((*ListResponse)(nil), "event.ListResponse")
	proto.RegisterType((*CreateRequest)(nil), "event.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "event.CreateResponse")
	proto.RegisterType((*DetailRequest)(nil), "event.DetailRequest")
	proto.RegisterType((*DetailResponse)(nil), "event.DetailResponse")
	proto.RegisterType((*UpdateRequest)(nil), "event.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "event.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "event.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "event.DeleteResponse")
	proto.RegisterType((*SearchRequest)(nil), "event.SearchRequest")
	proto.RegisterType((*SearchParams)(nil), "event.SearchParams")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 832 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x6a, 0xdc, 0x38,
	0x14, 0x66, 0xec, 0xf1, 0x78, 0xe6, 0xcc, 0x4f, 0x76, 0xb5, 0xd9, 0x45, 0x64, 0x61, 0x77, 0xea,
	0x8b, 0x32, 0xf4, 0x27, 0x6d, 0x27, 0x84, 0xdc, 0x15, 0xda, 0x34, 0xa4, 0x85, 0x5c, 0x04, 0x85,
	0x42, 0xe8, 0x9d, 0x62, 0x2b, 0x89, 0xa9, 0xc7, 0x72, 0x24, 0x4d, 0x60, 0x02, 0x7d, 0x87, 0xde,
	0xf6, 0x5d, 0xfa, 0x70, 0x45, 0x7f, 0x1e, 0x7b, 0x28, 0xa1, 0xa4, 0x77, 0x3a, 0x47, 0xe7, 0x3b,
	0xe7, 0x3b, 0x47, 0x9f, 0x64, 0xc3, 0x90, 0xdd, 0xb2, 0x52, 0xed, 0x56, 0x82, 0x2b, 0x8e, 0x22,
	0x63, 0x24, 0x13, 0x18, 0x11, 0x76, 0xb3, 0x64, 0x52, 0x1d, 0x2d, 0x2a, 0xb5, 0x4a, 0xfe, 0x85,
	0xf8, 0x34, 0x4f, 0xd5, 0x52, 0x30, 0xf4, 0x07, 0x84, 0x52, 0xa4, 0xb8, 0x33, 0xed, 0xcc, 0x06,
	0x44, 0x2f, 0x93, 0x0f, 0x10, 0x1f, 0xd3, 0xa2, 0x60, 0x62, 0x85, 0x10, 0x74, 0x17, 0x34, 0x2f,
	0xcd, 0x6e, 0x44, 0xcc, 0x1a, 0x3d, 0x81, 0x7e, 0x65, 0xb1, 0x12, 0x07, 0xd3, 0x70, 0x36, 0x9c,
	0x4f, 0x76, 0x6d, 0x49, 0x97, 0x92, 0xd4, 0xfb, 0xc9, 0x7f, 0xd0, 0x3f, 0xa4, 0x8a, 0x5d, 0x71,
	0x9b, 0xab, 0xa4, 0x0b, 0xe6, 0x2a, 0x99, 0x75, 0xf2, 0x12, 0xe0, 0x90, 0x73, 0x91, 0xe5, 0x25,
	0x55, 0x86, 0x4a, 0xc1, 0x6d, 0xb1, 0x80, 0xe8, 0xa5, 0xf1, 0x50, 0x85, 0x03, 0xe7, 0xa1, 0x2a,
	0x39, 0x80, 0xe8, 0x54, 0xe4, 0x29, 0xd3, 0xe9, 0x2e, 0xa8, 0xb4, 0xe9, 0x42, 0x62, 0xd6, 0x68,
	0x07, 0xfa, 0xe9, 0x52, 0x08, 0x56, 0xa6, 0x2b, 0x83, 0x19, 0x90, 0xda, 0x4e, 0x9e, 0x41, 0xf7,
	0x3d, 0x97, 0xea, 0x67, 0x34, 0xfc, 0x0c, 0x82, 0xf5, 0x0c, 0xbe, 0x40, 0xff, 0x84, 0xa7, 0x54,
	0xe5, 0xbc, 0x44, 0x18, 0x62, 0x9a, 0x65, 0x82, 0x49, 0xe9, 0x40, 0xde, 0xd4, 0xb8, 0xb4, 0xaa,
	0x71, 0x69, 0x95, 0xea, 0xec, 0x77, 0xbc, 0x64, 0x38, 0xb4, 0xd9, 0xf5, 0x1a, 0xbd, 0x02, 0x48,
	0xeb, 0x26, 0x71, 0x77, 0xda, 0x99, 0x0d, 0xe7, 0x7f, 0xba, 0x91, 0xad, 0xbb, 0x27, 0x8d, 0xa0,
	0xe4, 0x7b, 0x08, 0xd1, 0x91, 0x0e, 0x40, 0x13, 0x08, 0xf2, 0xcc, 0xd5, 0x0d, 0xf2, 0xac, 0xa6,
	0x1f, 0x34, 0xe8, 0x63, 0x88, 0xab, 0x82, 0xa6, 0x2c, 0xcf, 0x5c, 0x5d, 0x6f, 0xa2, 0x6d, 0x88,
	0xaa, 0x6b, 0xcd, 0xa7, 0x6b, 0xfc, 0xd6, 0xd0, 0x5e, 0xb6, 0xa0, 0x79, 0x81, 0x23, 0xeb, 0x35,
	0x86, 0x89, 0xd5, 0x30, 0xdc, 0x73, 0xb1, 0xda, 0xd0, 0xf5, 0x32, 0x4d, 0x3b, 0xb6, 0xf5, 0xf4,
	0x1a, 0xbd, 0x00, 0x48, 0xed, 0xa9, 0xe6, 0x4c, 0xe2, 0xbe, 0x69, 0x68, 0xcb, 0x37, 0xe4, 0x8e,
	0x9b, 0x34, 0x42, 0xd0, 0x14, 0x86, 0x19, 0x93, 0xa9, 0xc8, 0x2b, 0x3d, 0x50, 0x3c, 0x30, 0xb9,
	0x9a, 0x2e, 0x94, 0x40, 0x54, 0xe9, 0x63, 0xc5, 0x60, 0xb2, 0x8d, 0xbc, 0xa2, 0xb4, 0x8f, 0xd8,
	0x2d, 0xf4, 0x14, 0xfa, 0x85, 0x3b, 0x13, 0x3c, 0x6c, 0x15, 0xf5, 0x47, 0x45, 0xea, 0x00, 0x3d,
	0x93, 0xf2, 0xc2, 0xf6, 0x33, 0x32, 0x0a, 0xf1, 0xa6, 0xee, 0xb3, 0xc8, 0x3f, 0x33, 0x89, 0xc7,
	0xc6, 0x6f, 0x0d, 0x34, 0x83, 0xf8, 0xca, 0x8a, 0x1e, 0x4f, 0x4c, 0x6e, 0x2f, 0x6a, 0x77, 0x15,
	0x88, 0xdf, 0x46, 0x8f, 0x20, 0xba, 0xe6, 0x52, 0x49, 0xbc, 0x65, 0xc4, 0x3f, 0x74, 0x71, 0x5a,
	0x5c, 0xc4, 0xee, 0x24, 0x77, 0x30, 0x3a, 0xc9, 0xa5, 0x22, 0x4c, 0x56, 0xbc, 0x94, 0x0c, 0xfd,
	0x03, 0x3d, 0xa9, 0xa8, 0x5a, 0x4a, 0x77, 0x91, 0x9c, 0x65, 0x0e, 0x42, 0x08, 0x2e, 0xdc, 0x69,
	0x5a, 0x43, 0x7b, 0x15, 0x57, 0xb4, 0x30, 0x87, 0x19, 0x12, 0x6b, 0xa0, 0xc7, 0x10, 0x57, 0x74,
	0x55, 0x70, 0x9a, 0xe1, 0xae, 0x29, 0xec, 0x67, 0x64, 0x74, 0x42, 0xfc, 0x66, 0x72, 0x00, 0xe3,
	0x43, 0xc1, 0xb4, 0xa0, 0xec, 0x85, 0x6f, 0x02, 0x3b, 0xad, 0xe1, 0x6e, 0x00, 0xcf, 0x61, 0xe2,
	0x81, 0xbf, 0x4a, 0x3b, 0x6c, 0xd2, 0xc6, 0xeb, 0x3a, 0x81, 0x53, 0xa1, 0xcb, 0xfc, 0x3f, 0x8c,
	0xdf, 0x31, 0x45, 0xf3, 0xc2, 0x53, 0xb2, 0xa2, 0xee, 0x7a, 0x51, 0x27, 0x97, 0x30, 0xf1, 0x01,
	0x0f, 0x9a, 0x58, 0x6b, 0x36, 0xf7, 0xb4, 0x78, 0x0c, 0xe3, 0x8f, 0x55, 0xd6, 0x98, 0xcd, 0xe6,
	0xed, 0x6a, 0x24, 0x0a, 0xef, 0x4b, 0x74, 0x09, 0x13, 0x9f, 0xe8, 0x77, 0x09, 0xdf, 0x5b, 0xc7,
	0x4c, 0xae, 0x60, 0x9b, 0x84, 0xc3, 0x7a, 0x72, 0xe7, 0x7a, 0x72, 0x36, 0xe0, 0x41, 0x44, 0x70,
	0x9b, 0x48, 0x7f, 0x5d, 0xfa, 0x35, 0x8c, 0xcf, 0x18, 0x15, 0xe9, 0xb5, 0x2f, 0xfd, 0x7c, 0x53,
	0x47, 0x7f, 0x39, 0xce, 0x36, 0xec, 0x94, 0x0a, 0xba, 0x90, 0x6b, 0xfc, 0xd7, 0x0e, 0x8c, 0x9a,
	0x3b, 0x68, 0x04, 0x9d, 0x1b, 0x37, 0xea, 0xce, 0x8d, 0x7e, 0x57, 0x2e, 0x05, 0x5f, 0x18, 0x36,
	0x11, 0x31, 0x6b, 0xdd, 0x9c, 0xe2, 0x86, 0x47, 0x44, 0x02, 0xc5, 0xf5, 0x73, 0xae, 0xfd, 0x99,
	0x7f, 0x36, 0x07, 0xa4, 0xb6, 0x75, 0x9b, 0x8a, 0x9b, 0x1d, 0xfb, 0x88, 0x39, 0xcb, 0x7c, 0x02,
	0xdc, 0x13, 0x84, 0x7b, 0xd3, 0xd0, 0x7c, 0x02, 0x9c, 0x3d, 0xff, 0x16, 0xc0, 0xc8, 0x0c, 0xf8,
	0x8c, 0x89, 0x5b, 0xfd, 0xa2, 0xec, 0x41, 0xcf, 0x52, 0x44, 0xdb, 0xad, 0x5e, 0x5c, 0xcb, 0x3b,
	0xbe, 0xc3, 0xd6, 0x65, 0x9e, 0x43, 0x78, 0xcc, 0x54, 0x8d, 0x68, 0x29, 0x7b, 0xe7, 0xef, 0x0d,
	0xef, 0x1a, 0xf3, 0x26, 0xcb, 0x6a, 0x4c, 0xeb, 0x82, 0xd6, 0x98, 0x8d, 0xdb, 0xb7, 0x0f, 0x3d,
	0xab, 0xb1, 0x1a, 0xd6, 0xd2, 0x6e, 0x0d, 0xdb, 0x10, 0xe2, 0x3e, 0xf4, 0xac, 0x22, 0x1a, 0x0c,
	0x1b, 0x0a, 0x6a, 0x30, 0x6c, 0xca, 0xe6, 0x6d, 0xfc, 0xc9, 0xfe, 0x2a, 0x5c, 0xf4, 0xcc, 0x8f,
	0xc3, 0xde, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x22, 0x4e, 0x30, 0x47, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Get(ctx context.Context, in *DetailRequest, opts ...grpc.CallOption) (*DetailResponse, error)
	Add(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type eventServiceClient struct {
	cc *grpc.ClientConn
}

func NewEventServiceClient(cc *grpc.ClientConn) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/event.EventService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) Get(ctx context.Context, in *DetailRequest, opts ...grpc.CallOption) (*DetailResponse, error) {
	out := new(DetailResponse)
	err := c.cc.Invoke(ctx, "/event.EventService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) Add(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/event.EventService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/event.EventService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/event.EventService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
type EventServiceServer interface {
	Search(context.Context, *SearchRequest) (*ListResponse, error)
	Get(context.Context, *DetailRequest) (*DetailResponse, error)
	Add(context.Context, *CreateRequest) (*CreateResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

// UnimplementedEventServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEventServiceServer struct {
}

func (*UnimplementedEventServiceServer) Search(ctx context.Context, req *SearchRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedEventServiceServer) Get(ctx context.Context, req *DetailRequest) (*DetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedEventServiceServer) Add(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedEventServiceServer) Update(ctx context.Context, req *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedEventServiceServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterEventServiceServer(s *grpc.Server, srv EventServiceServer) {
	s.RegisterService(&_EventService_serviceDesc, srv)
}

func _EventService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Get(ctx, req.(*DetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Add(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "event.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _EventService_Search_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _EventService_Get_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _EventService_Add_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _EventService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _EventService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}
