// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package event

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *RequestEmpty) Reset()         { *m = RequestEmpty{} }
func (m *RequestEmpty) String() string { return proto.CompactTextString(m) }
func (*RequestEmpty) ProtoMessage()    {}
func (*RequestEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *RequestEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestEmpty.Unmarshal(m, b)
}
func (m *RequestEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestEmpty.Marshal(b, m, deterministic)
}
func (m *RequestEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestEmpty.Merge(m, src)
}
func (m *RequestEmpty) XXX_Size() int {
	return xxx_messageInfo_RequestEmpty.Size(m)
}
func (m *RequestEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_RequestEmpty proto.InternalMessageInfo

type Picture struct {
	// @inject_tag: bson:"src,omitempty"
	Src                  string   `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty" bson:"src,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Picture) Reset()         { *m = Picture{} }
func (m *Picture) String() string { return proto.CompactTextString(m) }
func (*Picture) ProtoMessage()    {}
func (*Picture) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *Picture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Picture.Unmarshal(m, b)
}
func (m *Picture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Picture.Marshal(b, m, deterministic)
}
func (m *Picture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Picture.Merge(m, src)
}
func (m *Picture) XXX_Size() int {
	return xxx_messageInfo_Picture.Size(m)
}
func (m *Picture) XXX_DiscardUnknown() {
	xxx_messageInfo_Picture.DiscardUnknown(m)
}

var xxx_messageInfo_Picture proto.InternalMessageInfo

func (m *Picture) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

type Gallery struct {
	// @inject_tag: bson:"main,omitempty"
	Main int32 `protobuf:"varint,1,opt,name=main,proto3" json:"main,omitempty" bson:"main,omitempty"`
	// @inject_tag: bson:"pictures,omitempty"
	Pictures             []*Picture `protobuf:"bytes,2,rep,name=pictures,proto3" json:"pictures,omitempty" bson:"pictures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-" bson:"-"`
	XXX_unrecognized     []byte     `json:"-" bson:"-"`
	XXX_sizecache        int32      `json:"-" bson:"-"`
}

func (m *Gallery) Reset()         { *m = Gallery{} }
func (m *Gallery) String() string { return proto.CompactTextString(m) }
func (*Gallery) ProtoMessage()    {}
func (*Gallery) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{2}
}

func (m *Gallery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gallery.Unmarshal(m, b)
}
func (m *Gallery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gallery.Marshal(b, m, deterministic)
}
func (m *Gallery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gallery.Merge(m, src)
}
func (m *Gallery) XXX_Size() int {
	return xxx_messageInfo_Gallery.Size(m)
}
func (m *Gallery) XXX_DiscardUnknown() {
	xxx_messageInfo_Gallery.DiscardUnknown(m)
}

var xxx_messageInfo_Gallery proto.InternalMessageInfo

func (m *Gallery) GetMain() int32 {
	if m != nil {
		return m.Main
	}
	return 0
}

func (m *Gallery) GetPictures() []*Picture {
	if m != nil {
		return m.Pictures
	}
	return nil
}

type Category struct {
	// @inject_tag: bson:"name,omitempty"
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" bson:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{3}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Coordinate struct {
	// @inject_tag: bson:"lng,omitempty"
	Lng float32 `protobuf:"fixed32,1,opt,name=lng,proto3" json:"lng,omitempty" bson:"lng,omitempty"`
	// @inject_tag: bson:"lat,omitempty"
	Lat                  float32  `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty" bson:"lat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{4}
}

func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (m *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(m, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *Coordinate) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

type Price struct {
	// @inject_tag: bson:"base,omitempty"
	Base int64 `protobuf:"varint,1,opt,name=base,proto3" json:"base,omitempty" bson:"base,omitempty"`
	// @inject_tag: bson:"currency,omitempty"
	Currency             string   `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty" bson:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Price) Reset()         { *m = Price{} }
func (m *Price) String() string { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()    {}
func (*Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{5}
}

func (m *Price) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Price.Unmarshal(m, b)
}
func (m *Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Price.Marshal(b, m, deterministic)
}
func (m *Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Price.Merge(m, src)
}
func (m *Price) XXX_Size() int {
	return xxx_messageInfo_Price.Size(m)
}
func (m *Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Price proto.InternalMessageInfo

func (m *Price) GetBase() int64 {
	if m != nil {
		return m.Base
	}
	return 0
}

func (m *Price) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type Artist struct {
	// @inject_tag: bson:"id,omitempty"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	// @inject_tag: bson:"name,omitempty"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" bson:"name,omitempty"`
	// @inject_tag: bson:"picture,omitempty"
	Picture              string   `protobuf:"bytes,3,opt,name=picture,proto3" json:"picture,omitempty" bson:"picture,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Artist) Reset()         { *m = Artist{} }
func (m *Artist) String() string { return proto.CompactTextString(m) }
func (*Artist) ProtoMessage()    {}
func (*Artist) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{6}
}

func (m *Artist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Artist.Unmarshal(m, b)
}
func (m *Artist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Artist.Marshal(b, m, deterministic)
}
func (m *Artist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Artist.Merge(m, src)
}
func (m *Artist) XXX_Size() int {
	return xxx_messageInfo_Artist.Size(m)
}
func (m *Artist) XXX_DiscardUnknown() {
	xxx_messageInfo_Artist.DiscardUnknown(m)
}

var xxx_messageInfo_Artist proto.InternalMessageInfo

func (m *Artist) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Artist) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Artist) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

type Place struct {
	// @inject_tag: bson:"id,omitempty"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	// @inject_tag: bson:"name,omitempty"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" bson:"name,omitempty"`
	// @inject_tag: bson:"logo,omitempty"
	Logo string `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty" bson:"logo,omitempty"`
	// @inject_tag: bson:"location,omitempty"
	Location *Location `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty" bson:"location,omitempty"`
	// @inject_tag: bson:"picture,omitempty"
	Picture              *Picture `protobuf:"bytes,5,opt,name=picture,proto3" json:"picture,omitempty" bson:"picture,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Place) Reset()         { *m = Place{} }
func (m *Place) String() string { return proto.CompactTextString(m) }
func (*Place) ProtoMessage()    {}
func (*Place) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{7}
}

func (m *Place) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Place.Unmarshal(m, b)
}
func (m *Place) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Place.Marshal(b, m, deterministic)
}
func (m *Place) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Place.Merge(m, src)
}
func (m *Place) XXX_Size() int {
	return xxx_messageInfo_Place.Size(m)
}
func (m *Place) XXX_DiscardUnknown() {
	xxx_messageInfo_Place.DiscardUnknown(m)
}

var xxx_messageInfo_Place proto.InternalMessageInfo

func (m *Place) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Place) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Place) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *Place) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Place) GetPicture() *Picture {
	if m != nil {
		return m.Picture
	}
	return nil
}

type Location struct {
	// @inject_tag: bson:"address,omitempty"
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty" bson:"address,omitempty"`
	// @inject_tag: bson:"cpc,omitempty"
	Cpc string `protobuf:"bytes,2,opt,name=cpc,proto3" json:"cpc,omitempty" bson:"cpc,omitempty"`
	// @inject_tag: bson:"zone,omitempty"
	Zone string `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty" bson:"zone,omitempty"`
	// @inject_tag: bson:"coordinate,omitempty"
	Coordinate           *Coordinate `protobuf:"bytes,4,opt,name=coordinate,proto3" json:"coordinate,omitempty" bson:"coordinate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-" bson:"-"`
	XXX_unrecognized     []byte      `json:"-" bson:"-"`
	XXX_sizecache        int32       `json:"-" bson:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{8}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Location) GetCpc() string {
	if m != nil {
		return m.Cpc
	}
	return ""
}

func (m *Location) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *Location) GetCoordinate() *Coordinate {
	if m != nil {
		return m.Coordinate
	}
	return nil
}

type Event struct {
	// @inject_tag: bson:"id,omitempty"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	// @inject_tag: bson:"name,omitempty"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" bson:"name,omitempty"`
	// @inject_tag: bson:"phone,omitempty"
	Phone string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty" bson:"phone,omitempty"`
	// @inject_tag: bson:"email,omitempty"
	Email string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty" bson:"email,omitempty"`
	// @inject_tag: bson:"place,omitempty"
	Place *Place `protobuf:"bytes,6,opt,name=place,proto3" json:"place,omitempty" bson:"place,omitempty"`
	// @inject_tag: bson:"date,omitempty"
	Date string `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty" bson:"date,omitempty"`
	// @inject_tag: bson:"categories,omitempty"
	Categories *Category `protobuf:"bytes,8,opt,name=categories,proto3" json:"categories,omitempty" bson:"categories,omitempty"`
	// @inject_tag: bson:"description,omitempty"
	Description string `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty" bson:"description,omitempty"`
	// @inject_tag: bson:"price,omitempty"
	Price *Price `protobuf:"bytes,10,opt,name=price,proto3" json:"price,omitempty" bson:"price,omitempty"`
	// @inject_tag: bson:"nbplace,omitempty"
	Nbplace int64 `protobuf:"varint,11,opt,name=nbplace,proto3" json:"nbplace,omitempty" bson:"nbplace,omitempty"`
	// @inject_tag: bson:"likes,omitempty"
	Likes int64 `protobuf:"varint,12,opt,name=likes,proto3" json:"likes,omitempty" bson:"likes,omitempty"`
	// @inject_tag: bson:"gallery,omitempty"
	Gallery *Gallery `protobuf:"bytes,13,opt,name=gallery,proto3" json:"gallery,omitempty" bson:"gallery,omitempty"`
	// @inject_tag: bson:"artists,omitempty"
	Artists []*Artist `protobuf:"bytes,14,rep,name=artists,proto3" json:"artists,omitempty" bson:"artists,omitempty"`
	// @inject_tag: bson:"hosts,omitempty"
	Hosts                []*Artist `protobuf:"bytes,15,rep,name=hosts,proto3" json:"hosts,omitempty" bson:"hosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-" bson:"-"`
	XXX_unrecognized     []byte    `json:"-" bson:"-"`
	XXX_sizecache        int32     `json:"-" bson:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{9}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Event) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Event) GetPlace() *Place {
	if m != nil {
		return m.Place
	}
	return nil
}

func (m *Event) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Event) GetCategories() *Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetPrice() *Price {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *Event) GetNbplace() int64 {
	if m != nil {
		return m.Nbplace
	}
	return 0
}

func (m *Event) GetLikes() int64 {
	if m != nil {
		return m.Likes
	}
	return 0
}

func (m *Event) GetGallery() *Gallery {
	if m != nil {
		return m.Gallery
	}
	return nil
}

func (m *Event) GetArtists() []*Artist {
	if m != nil {
		return m.Artists
	}
	return nil
}

func (m *Event) GetHosts() []*Artist {
	if m != nil {
		return m.Hosts
	}
	return nil
}

type ListResponse struct {
	// @inject_tag: bson:"status,omitempty"
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty" bson:"status,omitempty"`
	// @inject_tag: bson:"error,omitempty"
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty" bson:"error,omitempty"`
	// @inject_tag: bson:"total,omitempty"
	Total int64 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty" bson:"total,omitempty"`
	// @inject_tag: bson:"payload,omitempty"
	Payload              []*Event `protobuf:"bytes,4,rep,name=payload,proto3" json:"payload,omitempty" bson:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{10}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ListResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListResponse) GetPayload() []*Event {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateRequest struct {
	// @inject_tag: bson:"payload,omitempty"
	Payload              *Event   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty" bson:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{11}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetPayload() *Event {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateResponse struct {
	// @inject_tag: bson:"status,omitempty"
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty" bson:"status,omitempty"`
	// @inject_tag: bson:"error,omitempty"
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty" bson:"error,omitempty"`
	// @inject_tag: bson:"payload,omitempty"
	Payload              string   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty" bson:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{12}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateResponse) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type DetailRequest struct {
	// @inject_tag: bson:"id,omitempty"
	Id                   string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *DetailRequest) Reset()         { *m = DetailRequest{} }
func (m *DetailRequest) String() string { return proto.CompactTextString(m) }
func (*DetailRequest) ProtoMessage()    {}
func (*DetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{13}
}

func (m *DetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailRequest.Unmarshal(m, b)
}
func (m *DetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailRequest.Marshal(b, m, deterministic)
}
func (m *DetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailRequest.Merge(m, src)
}
func (m *DetailRequest) XXX_Size() int {
	return xxx_messageInfo_DetailRequest.Size(m)
}
func (m *DetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetailRequest proto.InternalMessageInfo

func (m *DetailRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DetailResponse struct {
	// @inject_tag: bson:"status,omitempty"
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty" bson:"status,omitempty"`
	// @inject_tag: bson:"error,omitempty"
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty" bson:"error,omitempty"`
	// @inject_tag: bson:"payload,omitempty"
	Payload              *Event   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty" bson:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *DetailResponse) Reset()         { *m = DetailResponse{} }
func (m *DetailResponse) String() string { return proto.CompactTextString(m) }
func (*DetailResponse) ProtoMessage()    {}
func (*DetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{14}
}

func (m *DetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailResponse.Unmarshal(m, b)
}
func (m *DetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailResponse.Marshal(b, m, deterministic)
}
func (m *DetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailResponse.Merge(m, src)
}
func (m *DetailResponse) XXX_Size() int {
	return xxx_messageInfo_DetailResponse.Size(m)
}
func (m *DetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetailResponse proto.InternalMessageInfo

func (m *DetailResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DetailResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DetailResponse) GetPayload() *Event {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateRequest struct {
	// @inject_tag: bson:"id,omitempty"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	// @inject_tag: bson:"payload,omitempty"
	Payload              *Event   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty" bson:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{15}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetPayload() *Event {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateResponse struct {
	// @inject_tag: bson:"status,omitempty"
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty" bson:"status,omitempty"`
	// @inject_tag: bson:"error,omitempty"
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty" bson:"error,omitempty"`
	// @inject_tag: bson:"payload,omitempty"
	Payload              bool     `protobuf:"varint,3,opt,name=payload,proto3" json:"payload,omitempty" bson:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{16}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UpdateResponse) GetPayload() bool {
	if m != nil {
		return m.Payload
	}
	return false
}

type UpdatePlaceRequest struct {
	// @inject_tag: bson:"id,omitempty"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	// @inject_tag: bson:"payload,omitempty"
	Payload              *Place   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty" bson:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *UpdatePlaceRequest) Reset()         { *m = UpdatePlaceRequest{} }
func (m *UpdatePlaceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePlaceRequest) ProtoMessage()    {}
func (*UpdatePlaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{17}
}

func (m *UpdatePlaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlaceRequest.Unmarshal(m, b)
}
func (m *UpdatePlaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlaceRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePlaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlaceRequest.Merge(m, src)
}
func (m *UpdatePlaceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePlaceRequest.Size(m)
}
func (m *UpdatePlaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlaceRequest proto.InternalMessageInfo

func (m *UpdatePlaceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdatePlaceRequest) GetPayload() *Place {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateLocationRequest struct {
	// @inject_tag: bson:"id,omitempty"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	// @inject_tag: bson:"payload,omitempty"
	Payload              *Location `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty" bson:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-" bson:"-"`
	XXX_unrecognized     []byte    `json:"-" bson:"-"`
	XXX_sizecache        int32     `json:"-" bson:"-"`
}

func (m *UpdateLocationRequest) Reset()         { *m = UpdateLocationRequest{} }
func (m *UpdateLocationRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateLocationRequest) ProtoMessage()    {}
func (*UpdateLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{18}
}

func (m *UpdateLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLocationRequest.Unmarshal(m, b)
}
func (m *UpdateLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLocationRequest.Marshal(b, m, deterministic)
}
func (m *UpdateLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLocationRequest.Merge(m, src)
}
func (m *UpdateLocationRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateLocationRequest.Size(m)
}
func (m *UpdateLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLocationRequest proto.InternalMessageInfo

func (m *UpdateLocationRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateLocationRequest) GetPayload() *Location {
	if m != nil {
		return m.Payload
	}
	return nil
}

type DeleteRequest struct {
	// @inject_tag: bson:"id,omitempty"
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{19}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	// @inject_tag: bson:"status,omitempty"
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty" bson:"status,omitempty"`
	// @inject_tag: bson:"error,omitempty"
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty" bson:"error,omitempty"`
	// @inject_tag: bson:"payload,omitempty"
	Payload              bool     `protobuf:"varint,3,opt,name=payload,proto3" json:"payload,omitempty" bson:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{20}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DeleteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DeleteResponse) GetPayload() bool {
	if m != nil {
		return m.Payload
	}
	return false
}

type SearchRequest struct {
	// @inject_tag: bson:"payload,omitempty"
	Payload              *SearchParams `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty" bson:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-" bson:"-"`
	XXX_unrecognized     []byte        `json:"-" bson:"-"`
	XXX_sizecache        int32         `json:"-" bson:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{21}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetPayload() *SearchParams {
	if m != nil {
		return m.Payload
	}
	return nil
}

type SearchParams struct {
	// @inject_tag: bson:"q,omitempty"
	Q string `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty" bson:"q,omitempty"`
	// @inject_tag: bson:"from,omitempty"
	From int32 `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty" bson:"from,omitempty"`
	// @inject_tag: bson:"to,omitempty"
	To int32 `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty" bson:"to,omitempty"`
	// @inject_tag: bson:"fromdate,omitempty"
	Fromdate string `protobuf:"bytes,4,opt,name=fromdate,proto3" json:"fromdate,omitempty" bson:"fromdate,omitempty"`
	// @inject_tag: bson:"todate,omitempty"
	Todate string `protobuf:"bytes,5,opt,name=todate,proto3" json:"todate,omitempty" bson:"todate,omitempty"`
	// @inject_tag: bson:"category,omitempty"
	Category             []string `protobuf:"bytes,6,rep,name=category,proto3" json:"category,omitempty" bson:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *SearchParams) Reset()         { *m = SearchParams{} }
func (m *SearchParams) String() string { return proto.CompactTextString(m) }
func (*SearchParams) ProtoMessage()    {}
func (*SearchParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{22}
}

func (m *SearchParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchParams.Unmarshal(m, b)
}
func (m *SearchParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchParams.Marshal(b, m, deterministic)
}
func (m *SearchParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchParams.Merge(m, src)
}
func (m *SearchParams) XXX_Size() int {
	return xxx_messageInfo_SearchParams.Size(m)
}
func (m *SearchParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchParams.DiscardUnknown(m)
}

var xxx_messageInfo_SearchParams proto.InternalMessageInfo

func (m *SearchParams) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *SearchParams) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *SearchParams) GetTo() int32 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *SearchParams) GetFromdate() string {
	if m != nil {
		return m.Fromdate
	}
	return ""
}

func (m *SearchParams) GetTodate() string {
	if m != nil {
		return m.Todate
	}
	return ""
}

func (m *SearchParams) GetCategory() []string {
	if m != nil {
		return m.Category
	}
	return nil
}

func init() {
	proto.RegisterType((*RequestEmpty)(nil), "event.RequestEmpty")
	proto.RegisterType((*Picture)(nil), "event.Picture")
	proto.RegisterType((*Gallery)(nil), "event.Gallery")
	proto.RegisterType((*Category)(nil), "event.Category")
	proto.RegisterType((*Coordinate)(nil), "event.Coordinate")
	proto.RegisterType((*Price)(nil), "event.Price")
	proto.RegisterType((*Artist)(nil), "event.Artist")
	proto.RegisterType((*Place)(nil), "event.Place")
	proto.RegisterType((*Location)(nil), "event.Location")
	proto.RegisterType((*Event)(nil), "event.Event")
	proto.RegisterType((*ListResponse)(nil), "event.ListResponse")
	proto.RegisterType((*CreateRequest)(nil), "event.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "event.CreateResponse")
	proto.RegisterType((*DetailRequest)(nil), "event.DetailRequest")
	proto.RegisterType((*DetailResponse)(nil), "event.DetailResponse")
	proto.RegisterType((*UpdateRequest)(nil), "event.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "event.UpdateResponse")
	proto.RegisterType((*UpdatePlaceRequest)(nil), "event.UpdatePlaceRequest")
	proto.RegisterType((*UpdateLocationRequest)(nil), "event.UpdateLocationRequest")
	proto.RegisterType((*DeleteRequest)(nil), "event.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "event.DeleteResponse")
	proto.RegisterType((*SearchRequest)(nil), "event.SearchRequest")
	proto.RegisterType((*SearchParams)(nil), "event.SearchParams")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 899 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdb, 0x6e, 0xdc, 0x44,
	0x18, 0xd6, 0xda, 0xeb, 0x3d, 0xfc, 0x7b, 0x28, 0x0c, 0x2d, 0x1a, 0x05, 0x04, 0x2b, 0x23, 0x41,
	0x00, 0x51, 0x20, 0x15, 0xea, 0x1d, 0x52, 0x09, 0x21, 0x42, 0xca, 0x45, 0x34, 0x15, 0x52, 0xc5,
	0xdd, 0xc4, 0x9e, 0x26, 0x16, 0x5e, 0x8f, 0x33, 0x33, 0xa9, 0xb4, 0x95, 0x78, 0x07, 0xae, 0x78,
	0x0c, 0x9e, 0x89, 0x47, 0x41, 0xf3, 0xcf, 0x61, 0x6d, 0x13, 0xda, 0x28, 0xe2, 0x6e, 0xfe, 0xf3,
	0xf7, 0x1f, 0x6d, 0x58, 0x88, 0x57, 0xa2, 0x31, 0x8f, 0x5b, 0x25, 0x8d, 0x24, 0x19, 0x12, 0xf9,
	0x1a, 0x96, 0x4c, 0x5c, 0xdf, 0x08, 0x6d, 0x4e, 0xb6, 0xad, 0xd9, 0xe5, 0x1f, 0xc0, 0xf4, 0xbc,
	0x2a, 0xcc, 0x8d, 0x12, 0xe4, 0x1d, 0x48, 0xb5, 0x2a, 0xe8, 0x68, 0x33, 0x3a, 0x9c, 0x33, 0xfb,
	0xcc, 0x7f, 0x86, 0xe9, 0x29, 0xaf, 0x6b, 0xa1, 0x76, 0x84, 0xc0, 0x78, 0xcb, 0xab, 0x06, 0xa5,
	0x19, 0xc3, 0x37, 0xf9, 0x02, 0x66, 0xad, 0xb3, 0xd5, 0x34, 0xd9, 0xa4, 0x87, 0x8b, 0xa3, 0xf5,
	0x63, 0x17, 0xd2, 0xbb, 0x64, 0x51, 0x9e, 0x7f, 0x04, 0xb3, 0x63, 0x6e, 0xc4, 0xa5, 0x74, 0xbe,
	0x1a, 0xbe, 0x15, 0x3e, 0x12, 0xbe, 0xf3, 0x6f, 0x00, 0x8e, 0xa5, 0x54, 0x65, 0xd5, 0x70, 0x83,
	0x50, 0xea, 0xe6, 0x12, 0x15, 0x12, 0x66, 0x9f, 0xc8, 0xe1, 0x86, 0x26, 0x9e, 0xc3, 0x4d, 0xfe,
	0x14, 0xb2, 0x73, 0x55, 0x15, 0xc2, 0xba, 0xbb, 0xe0, 0xda, 0xb9, 0x4b, 0x19, 0xbe, 0xc9, 0x01,
	0xcc, 0x8a, 0x1b, 0xa5, 0x44, 0x53, 0xec, 0xd0, 0x66, 0xce, 0x22, 0x9d, 0xff, 0x04, 0x93, 0x67,
	0xca, 0x54, 0xda, 0x90, 0x35, 0x24, 0x55, 0xe9, 0x61, 0x24, 0x55, 0x19, 0x81, 0x25, 0x7b, 0x60,
	0x84, 0xc2, 0xd4, 0x27, 0x41, 0x53, 0x64, 0x07, 0x32, 0xff, 0x73, 0x04, 0xd9, 0x79, 0xcd, 0x0b,
	0x71, 0x27, 0x3f, 0x04, 0xc6, 0xb5, 0xbc, 0x94, 0xde, 0x09, 0xbe, 0xc9, 0x97, 0x30, 0xab, 0x65,
	0xc1, 0x4d, 0x25, 0x1b, 0x3a, 0xde, 0x8c, 0x0e, 0x17, 0x47, 0x0f, 0x7c, 0x01, 0xcf, 0x3c, 0x9b,
	0x45, 0x05, 0x72, 0xb8, 0x07, 0x92, 0xa1, 0xee, 0xb0, 0xd8, 0x11, 0xd8, 0xef, 0x30, 0x0b, 0xf6,
	0x16, 0x3e, 0x2f, 0x4b, 0x25, 0xb4, 0xf6, 0xf8, 0x02, 0x69, 0x2b, 0x5a, 0xb4, 0x85, 0xc7, 0x68,
	0x9f, 0x16, 0xe2, 0x6b, 0xd9, 0x84, 0x3c, 0xf1, 0x4d, 0xbe, 0x05, 0x28, 0x62, 0x5f, 0x3c, 0xc8,
	0x77, 0x7d, 0xe0, 0x7d, 0xc3, 0x58, 0x47, 0x29, 0xff, 0x2b, 0x85, 0xec, 0xc4, 0x2a, 0xdc, 0xa9,
	0x2e, 0x0f, 0x21, 0x6b, 0xaf, 0x6c, 0xd4, 0x31, 0x32, 0x1d, 0x61, 0xb9, 0x62, 0xcb, 0xab, 0x1a,
	0x53, 0x9d, 0x33, 0x47, 0x90, 0x1c, 0xb2, 0xd6, 0x16, 0x9c, 0x4e, 0x10, 0xc7, 0x32, 0x14, 0xc0,
	0xf2, 0x98, 0x13, 0xd9, 0x18, 0xa5, 0x85, 0x3a, 0x75, 0x31, 0xec, 0x9b, 0x7c, 0x0d, 0x50, 0xb8,
	0xe1, 0xab, 0x84, 0xa6, 0xb3, 0x5e, 0xa5, 0xc3, 0x54, 0xb2, 0x8e, 0x0a, 0xd9, 0xc0, 0xa2, 0x14,
	0xba, 0x50, 0x55, 0x8b, 0xbd, 0x99, 0xa3, 0xaf, 0x2e, 0x0b, 0xa1, 0xd8, 0xe9, 0xa3, 0xd0, 0x87,
	0x62, 0x79, 0xcc, 0x89, 0x6c, 0xed, 0x9b, 0x0b, 0x07, 0x78, 0x81, 0xb3, 0x19, 0x48, 0x9b, 0x5e,
	0x5d, 0xfd, 0x26, 0x34, 0x5d, 0x22, 0xdf, 0x11, 0xb6, 0xc3, 0x97, 0x6e, 0xdd, 0xe8, 0xaa, 0xd7,
	0x61, 0xbf, 0x84, 0x2c, 0x88, 0xc9, 0x67, 0x30, 0xe5, 0x38, 0xc2, 0x9a, 0xae, 0x71, 0xf1, 0x56,
	0x5e, 0xd3, 0x0d, 0x36, 0x0b, 0x52, 0xf2, 0x09, 0x64, 0x57, 0xd2, 0xaa, 0x3d, 0xb8, 0x4d, 0xcd,
	0xc9, 0xf2, 0xd7, 0xb0, 0x3c, 0xb3, 0xa4, 0xd0, 0xad, 0x6c, 0xb4, 0x20, 0xef, 0xc3, 0x44, 0x1b,
	0x6e, 0x6e, 0xb4, 0xdf, 0x76, 0x4f, 0x61, 0x53, 0x94, 0x92, 0xca, 0xf7, 0xcf, 0x11, 0x96, 0x6b,
	0xa4, 0xe1, 0x35, 0x8e, 0x4d, 0xca, 0x1c, 0x41, 0x3e, 0x85, 0x69, 0xcb, 0x77, 0xb5, 0xe4, 0x25,
	0x1d, 0x63, 0xe8, 0x50, 0x21, 0x9c, 0x0c, 0x16, 0x84, 0xf9, 0x53, 0x58, 0x1d, 0x2b, 0x61, 0x47,
	0xc8, 0x5d, 0xa5, 0xae, 0xe1, 0xa8, 0x57, 0xda, 0x81, 0xe1, 0x0b, 0x58, 0x07, 0xc3, 0xbb, 0xc2,
	0x4e, 0xbb, 0xb0, 0xe9, 0x3e, 0x4e, 0xe2, 0xf7, 0xda, 0x7b, 0xfe, 0x18, 0x56, 0x3f, 0x0a, 0xc3,
	0xab, 0x3a, 0x40, 0x72, 0x63, 0x3c, 0x0e, 0x63, 0x9c, 0xbf, 0x84, 0x75, 0x50, 0xb8, 0x57, 0xc5,
	0x7a, 0xb5, 0x79, 0x43, 0x8a, 0xa7, 0xb0, 0xfa, 0xa5, 0x2d, 0x3b, 0xb5, 0x19, 0xee, 0x53, 0xc7,
	0x51, 0xfa, 0x96, 0x5a, 0x05, 0x47, 0xf7, 0x02, 0x4c, 0xfb, 0x71, 0x66, 0x7b, 0xcf, 0x67, 0x40,
	0x9c, 0x67, 0xb7, 0x83, 0x6f, 0xc7, 0x99, 0xdc, 0xb2, 0xb9, 0xd1, 0x1b, 0x83, 0x47, 0xce, 0x5b,
	0x3c, 0x7f, 0xff, 0xe1, 0xf0, 0xf3, 0xa1, 0xc3, 0x7f, 0xdd, 0xcd, 0x7e, 0x37, 0x6b, 0x31, 0x2c,
	0x62, 0x1a, 0xbb, 0xf9, 0xc2, 0x76, 0xd3, 0x29, 0xfc, 0xcf, 0xc5, 0xf9, 0x1e, 0x56, 0xcf, 0x05,
	0x57, 0xc5, 0x55, 0x08, 0xfd, 0xd5, 0x70, 0xb6, 0xdf, 0xf3, 0xb0, 0x9d, 0xda, 0x39, 0x57, 0x7c,
	0xab, 0xf7, 0xf6, 0x7f, 0x8c, 0x60, 0xd9, 0x95, 0x90, 0x25, 0x8c, 0xae, 0x7d, 0x15, 0x46, 0xd7,
	0xf6, 0xd2, 0xbd, 0x54, 0x72, 0x8b, 0x68, 0x32, 0x86, 0x6f, 0x9b, 0x9c, 0x71, 0xdf, 0x98, 0x8c,
	0x25, 0x46, 0xda, 0xef, 0xa0, 0xe5, 0x97, 0xe1, 0x78, 0xcf, 0x59, 0xa4, 0x6d, 0x9a, 0x46, 0xa2,
	0xc4, 0x1d, 0x59, 0x4f, 0xe1, 0xb7, 0xd3, 0x1f, 0x45, 0x3a, 0xd9, 0xa4, 0xf8, 0xed, 0xf4, 0xf4,
	0xd1, 0xdf, 0x09, 0x2c, 0x71, 0xb8, 0x9e, 0x0b, 0xf5, 0xca, 0xde, 0xb8, 0x27, 0x30, 0x71, 0x10,
	0xc9, 0xc3, 0x5e, 0x2e, 0x3e, 0xe5, 0x83, 0x90, 0x61, 0xef, 0xc0, 0x1c, 0x41, 0x7a, 0x2a, 0x4c,
	0xb4, 0xe8, 0x6d, 0xdb, 0xc1, 0xa3, 0x01, 0x77, 0x6f, 0xf3, 0xac, 0x2c, 0xa3, 0x4d, 0xef, 0x68,
	0x44, 0x9b, 0xc1, 0x45, 0x38, 0x09, 0x73, 0x1f, 0x3f, 0x87, 0x1f, 0x7a, 0xc5, 0x5b, 0xc7, 0x2c,
	0xba, 0x19, 0x2c, 0xcb, 0x77, 0x30, 0x71, 0x9c, 0x18, 0xbd, 0xb7, 0x96, 0x6f, 0x30, 0x73, 0x83,
	0xd5, 0x49, 0xb4, 0x33, 0x88, 0x9d, 0x44, 0xbb, 0xd3, 0xf7, 0xc3, 0xf4, 0x57, 0xf7, 0xab, 0x76,
	0x31, 0xc1, 0x1f, 0xb7, 0x27, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xee, 0x14, 0xa2, 0x9e, 0xc7,
	0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Get(ctx context.Context, in *DetailRequest, opts ...grpc.CallOption) (*DetailResponse, error)
	Add(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	UpdateLocation(ctx context.Context, in *UpdateLocationRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type eventServiceClient struct {
	cc *grpc.ClientConn
}

func NewEventServiceClient(cc *grpc.ClientConn) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/event.EventService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) Get(ctx context.Context, in *DetailRequest, opts ...grpc.CallOption) (*DetailResponse, error) {
	out := new(DetailResponse)
	err := c.cc.Invoke(ctx, "/event.EventService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) Add(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/event.EventService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) UpdateLocation(ctx context.Context, in *UpdateLocationRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/event.EventService/UpdateLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/event.EventService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/event.EventService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
type EventServiceServer interface {
	Search(context.Context, *SearchRequest) (*ListResponse, error)
	Get(context.Context, *DetailRequest) (*DetailResponse, error)
	Add(context.Context, *CreateRequest) (*CreateResponse, error)
	UpdateLocation(context.Context, *UpdateLocationRequest) (*UpdateResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

// UnimplementedEventServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEventServiceServer struct {
}

func (*UnimplementedEventServiceServer) Search(ctx context.Context, req *SearchRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedEventServiceServer) Get(ctx context.Context, req *DetailRequest) (*DetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedEventServiceServer) Add(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedEventServiceServer) UpdateLocation(ctx context.Context, req *UpdateLocationRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLocation not implemented")
}
func (*UnimplementedEventServiceServer) Update(ctx context.Context, req *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedEventServiceServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterEventServiceServer(s *grpc.Server, srv EventServiceServer) {
	s.RegisterService(&_EventService_serviceDesc, srv)
}

func _EventService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Get(ctx, req.(*DetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Add(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_UpdateLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).UpdateLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/UpdateLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).UpdateLocation(ctx, req.(*UpdateLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "event.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _EventService_Search_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _EventService_Get_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _EventService_Add_Handler,
		},
		{
			MethodName: "UpdateLocation",
			Handler:    _EventService_UpdateLocation_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _EventService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _EventService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}
