// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package product

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestEmpty) Reset()         { *m = RequestEmpty{} }
func (m *RequestEmpty) String() string { return proto.CompactTextString(m) }
func (*RequestEmpty) ProtoMessage()    {}
func (*RequestEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

func (m *RequestEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestEmpty.Unmarshal(m, b)
}
func (m *RequestEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestEmpty.Marshal(b, m, deterministic)
}
func (m *RequestEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestEmpty.Merge(m, src)
}
func (m *RequestEmpty) XXX_Size() int {
	return xxx_messageInfo_RequestEmpty.Size(m)
}
func (m *RequestEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_RequestEmpty proto.InternalMessageInfo

type Gastronomie struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gastronomie) Reset()         { *m = Gastronomie{} }
func (m *Gastronomie) String() string { return proto.CompactTextString(m) }
func (*Gastronomie) ProtoMessage()    {}
func (*Gastronomie) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{1}
}

func (m *Gastronomie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gastronomie.Unmarshal(m, b)
}
func (m *Gastronomie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gastronomie.Marshal(b, m, deterministic)
}
func (m *Gastronomie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gastronomie.Merge(m, src)
}
func (m *Gastronomie) XXX_Size() int {
	return xxx_messageInfo_Gastronomie.Size(m)
}
func (m *Gastronomie) XXX_DiscardUnknown() {
	xxx_messageInfo_Gastronomie.DiscardUnknown(m)
}

var xxx_messageInfo_Gastronomie proto.InternalMessageInfo

func (m *Gastronomie) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Coordinate struct {
	Lon                  float32  `protobuf:"fixed32,1,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat                  float32  `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{2}
}

func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (m *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(m, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *Coordinate) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

type Accompaniment struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Accompaniment) Reset()         { *m = Accompaniment{} }
func (m *Accompaniment) String() string { return proto.CompactTextString(m) }
func (*Accompaniment) ProtoMessage()    {}
func (*Accompaniment) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{3}
}

func (m *Accompaniment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Accompaniment.Unmarshal(m, b)
}
func (m *Accompaniment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Accompaniment.Marshal(b, m, deterministic)
}
func (m *Accompaniment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Accompaniment.Merge(m, src)
}
func (m *Accompaniment) XXX_Size() int {
	return xxx_messageInfo_Accompaniment.Size(m)
}
func (m *Accompaniment) XXX_DiscardUnknown() {
	xxx_messageInfo_Accompaniment.DiscardUnknown(m)
}

var xxx_messageInfo_Accompaniment proto.InternalMessageInfo

func (m *Accompaniment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Picture struct {
	Src                  string   `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Picture) Reset()         { *m = Picture{} }
func (m *Picture) String() string { return proto.CompactTextString(m) }
func (*Picture) ProtoMessage()    {}
func (*Picture) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{4}
}

func (m *Picture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Picture.Unmarshal(m, b)
}
func (m *Picture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Picture.Marshal(b, m, deterministic)
}
func (m *Picture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Picture.Merge(m, src)
}
func (m *Picture) XXX_Size() int {
	return xxx_messageInfo_Picture.Size(m)
}
func (m *Picture) XXX_DiscardUnknown() {
	xxx_messageInfo_Picture.DiscardUnknown(m)
}

var xxx_messageInfo_Picture proto.InternalMessageInfo

func (m *Picture) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

type Gallery struct {
	Main                 int32      `protobuf:"varint,1,opt,name=main,proto3" json:"main,omitempty"`
	Pictures             []*Picture `protobuf:"bytes,2,rep,name=pictures,proto3" json:"pictures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Gallery) Reset()         { *m = Gallery{} }
func (m *Gallery) String() string { return proto.CompactTextString(m) }
func (*Gallery) ProtoMessage()    {}
func (*Gallery) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{5}
}

func (m *Gallery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gallery.Unmarshal(m, b)
}
func (m *Gallery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gallery.Marshal(b, m, deterministic)
}
func (m *Gallery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gallery.Merge(m, src)
}
func (m *Gallery) XXX_Size() int {
	return xxx_messageInfo_Gallery.Size(m)
}
func (m *Gallery) XXX_DiscardUnknown() {
	xxx_messageInfo_Gallery.DiscardUnknown(m)
}

var xxx_messageInfo_Gallery proto.InternalMessageInfo

func (m *Gallery) GetMain() int32 {
	if m != nil {
		return m.Main
	}
	return 0
}

func (m *Gallery) GetPictures() []*Picture {
	if m != nil {
		return m.Pictures
	}
	return nil
}

type Price struct {
	Base                 int64    `protobuf:"varint,1,opt,name=base,proto3" json:"base,omitempty"`
	Currency             string   `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Price) Reset()         { *m = Price{} }
func (m *Price) String() string { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()    {}
func (*Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{6}
}

func (m *Price) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Price.Unmarshal(m, b)
}
func (m *Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Price.Marshal(b, m, deterministic)
}
func (m *Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Price.Merge(m, src)
}
func (m *Price) XXX_Size() int {
	return xxx_messageInfo_Price.Size(m)
}
func (m *Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Price proto.InternalMessageInfo

func (m *Price) GetBase() int64 {
	if m != nil {
		return m.Base
	}
	return 0
}

func (m *Price) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type Category struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{7}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Location struct {
	Address              string      `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Cpc                  string      `protobuf:"bytes,2,opt,name=cpc,proto3" json:"cpc,omitempty"`
	Zone                 string      `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	Location             *Coordinate `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{8}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Location) GetCpc() string {
	if m != nil {
		return m.Cpc
	}
	return ""
}

func (m *Location) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *Location) GetLocation() *Coordinate {
	if m != nil {
		return m.Location
	}
	return nil
}

type Schedule struct {
	Date                 string   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	StartAm              string   `protobuf:"bytes,2,opt,name=start_am,json=startAm,proto3" json:"start_am,omitempty"`
	EndAm                string   `protobuf:"bytes,3,opt,name=end_am,json=endAm,proto3" json:"end_am,omitempty"`
	StartPm              string   `protobuf:"bytes,4,opt,name=start_pm,json=startPm,proto3" json:"start_pm,omitempty"`
	EndPm                string   `protobuf:"bytes,5,opt,name=end_pm,json=endPm,proto3" json:"end_pm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Schedule) Reset()         { *m = Schedule{} }
func (m *Schedule) String() string { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()    {}
func (*Schedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{9}
}

func (m *Schedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schedule.Unmarshal(m, b)
}
func (m *Schedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schedule.Marshal(b, m, deterministic)
}
func (m *Schedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schedule.Merge(m, src)
}
func (m *Schedule) XXX_Size() int {
	return xxx_messageInfo_Schedule.Size(m)
}
func (m *Schedule) XXX_DiscardUnknown() {
	xxx_messageInfo_Schedule.DiscardUnknown(m)
}

var xxx_messageInfo_Schedule proto.InternalMessageInfo

func (m *Schedule) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Schedule) GetStartAm() string {
	if m != nil {
		return m.StartAm
	}
	return ""
}

func (m *Schedule) GetEndAm() string {
	if m != nil {
		return m.EndAm
	}
	return ""
}

func (m *Schedule) GetStartPm() string {
	if m != nil {
		return m.StartPm
	}
	return ""
}

func (m *Schedule) GetEndPm() string {
	if m != nil {
		return m.EndPm
	}
	return ""
}

type Product struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string           `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	PlaceRef             string           `protobuf:"bytes,3,opt,name=place_ref,json=placeRef,proto3" json:"place_ref,omitempty"`
	PlaceName            string           `protobuf:"bytes,4,opt,name=place_name,json=placeName,proto3" json:"place_name,omitempty"`
	PlaceLogo            string           `protobuf:"bytes,5,opt,name=place_logo,json=placeLogo,proto3" json:"place_logo,omitempty"`
	Category             string           `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Price                int32            `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	Phone                string           `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	Description          string           `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Gastronomie          []*Gastronomie   `protobuf:"bytes,10,rep,name=gastronomie,proto3" json:"gastronomie,omitempty"`
	Location             *Location        `protobuf:"bytes,11,opt,name=location,proto3" json:"location,omitempty"`
	Likes                int64            `protobuf:"varint,12,opt,name=likes,proto3" json:"likes,omitempty"`
	Recipes              []string         `protobuf:"bytes,13,rep,name=recipes,proto3" json:"recipes,omitempty"`
	Accompaniment        []*Accompaniment `protobuf:"bytes,14,rep,name=accompaniment,proto3" json:"accompaniment,omitempty"`
	Discount             int32            `protobuf:"varint,15,opt,name=discount,proto3" json:"discount,omitempty"`
	Size                 string           `protobuf:"bytes,16,opt,name=size,proto3" json:"size,omitempty"`
	Quantity             int32            `protobuf:"varint,17,opt,name=quantity,proto3" json:"quantity,omitempty"`
	SpicyLevel           int32            `protobuf:"varint,18,opt,name=spicy_level,json=spicyLevel,proto3" json:"spicy_level,omitempty"`
	Gallery              *Gallery         `protobuf:"bytes,20,opt,name=gallery,proto3" json:"gallery,omitempty"`
	Schedule             []*Schedule      `protobuf:"bytes,21,rep,name=schedule,proto3" json:"schedule,omitempty"`
	Notation             int32            `protobuf:"varint,22,opt,name=notation,proto3" json:"notation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{10}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetPlaceRef() string {
	if m != nil {
		return m.PlaceRef
	}
	return ""
}

func (m *Product) GetPlaceName() string {
	if m != nil {
		return m.PlaceName
	}
	return ""
}

func (m *Product) GetPlaceLogo() string {
	if m != nil {
		return m.PlaceLogo
	}
	return ""
}

func (m *Product) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Product) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetGastronomie() []*Gastronomie {
	if m != nil {
		return m.Gastronomie
	}
	return nil
}

func (m *Product) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Product) GetLikes() int64 {
	if m != nil {
		return m.Likes
	}
	return 0
}

func (m *Product) GetRecipes() []string {
	if m != nil {
		return m.Recipes
	}
	return nil
}

func (m *Product) GetAccompaniment() []*Accompaniment {
	if m != nil {
		return m.Accompaniment
	}
	return nil
}

func (m *Product) GetDiscount() int32 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *Product) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *Product) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Product) GetSpicyLevel() int32 {
	if m != nil {
		return m.SpicyLevel
	}
	return 0
}

func (m *Product) GetGallery() *Gallery {
	if m != nil {
		return m.Gallery
	}
	return nil
}

func (m *Product) GetSchedule() []*Schedule {
	if m != nil {
		return m.Schedule
	}
	return nil
}

func (m *Product) GetNotation() int32 {
	if m != nil {
		return m.Notation
	}
	return 0
}

type ListResponse struct {
	Status               int32      `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Total                int64      `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*Product `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{11}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ListResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListResponse) GetData() []*Product {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateRequest struct {
	Payload              *Product `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{12}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetPayload() *Product {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Payload              string   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{13}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateResponse) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type DetailRequest struct {
	Id                   string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailRequest) Reset()         { *m = DetailRequest{} }
func (m *DetailRequest) String() string { return proto.CompactTextString(m) }
func (*DetailRequest) ProtoMessage()    {}
func (*DetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{14}
}

func (m *DetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailRequest.Unmarshal(m, b)
}
func (m *DetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailRequest.Marshal(b, m, deterministic)
}
func (m *DetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailRequest.Merge(m, src)
}
func (m *DetailRequest) XXX_Size() int {
	return xxx_messageInfo_DetailRequest.Size(m)
}
func (m *DetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetailRequest proto.InternalMessageInfo

func (m *DetailRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DetailResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Payload              *Product `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailResponse) Reset()         { *m = DetailResponse{} }
func (m *DetailResponse) String() string { return proto.CompactTextString(m) }
func (*DetailResponse) ProtoMessage()    {}
func (*DetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{15}
}

func (m *DetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailResponse.Unmarshal(m, b)
}
func (m *DetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailResponse.Marshal(b, m, deterministic)
}
func (m *DetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailResponse.Merge(m, src)
}
func (m *DetailResponse) XXX_Size() int {
	return xxx_messageInfo_DetailResponse.Size(m)
}
func (m *DetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetailResponse proto.InternalMessageInfo

func (m *DetailResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DetailResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DetailResponse) GetPayload() *Product {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload              *Product `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{16}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetPayload() *Product {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Payload              *Product `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{17}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UpdateResponse) GetPayload() *Product {
	if m != nil {
		return m.Payload
	}
	return nil
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{18}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Payload              bool     `protobuf:"varint,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{19}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DeleteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DeleteResponse) GetPayload() bool {
	if m != nil {
		return m.Payload
	}
	return false
}

type SearchRequest struct {
	Payload              *SearchParams `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{20}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetPayload() *SearchParams {
	if m != nil {
		return m.Payload
	}
	return nil
}

type SearchParams struct {
	Q                    string   `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	From                 int32    `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   int32    `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	Fromdate             string   `protobuf:"bytes,4,opt,name=fromdate,proto3" json:"fromdate,omitempty"`
	Todate               string   `protobuf:"bytes,5,opt,name=todate,proto3" json:"todate,omitempty"`
	Category             []string `protobuf:"bytes,6,rep,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchParams) Reset()         { *m = SearchParams{} }
func (m *SearchParams) String() string { return proto.CompactTextString(m) }
func (*SearchParams) ProtoMessage()    {}
func (*SearchParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{21}
}

func (m *SearchParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchParams.Unmarshal(m, b)
}
func (m *SearchParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchParams.Marshal(b, m, deterministic)
}
func (m *SearchParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchParams.Merge(m, src)
}
func (m *SearchParams) XXX_Size() int {
	return xxx_messageInfo_SearchParams.Size(m)
}
func (m *SearchParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchParams.DiscardUnknown(m)
}

var xxx_messageInfo_SearchParams proto.InternalMessageInfo

func (m *SearchParams) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *SearchParams) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *SearchParams) GetTo() int32 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *SearchParams) GetFromdate() string {
	if m != nil {
		return m.Fromdate
	}
	return ""
}

func (m *SearchParams) GetTodate() string {
	if m != nil {
		return m.Todate
	}
	return ""
}

func (m *SearchParams) GetCategory() []string {
	if m != nil {
		return m.Category
	}
	return nil
}

func init() {
	proto.RegisterType((*RequestEmpty)(nil), "product.RequestEmpty")
	proto.RegisterType((*Gastronomie)(nil), "product.Gastronomie")
	proto.RegisterType((*Coordinate)(nil), "product.Coordinate")
	proto.RegisterType((*Accompaniment)(nil), "product.Accompaniment")
	proto.RegisterType((*Picture)(nil), "product.Picture")
	proto.RegisterType((*Gallery)(nil), "product.Gallery")
	proto.RegisterType((*Price)(nil), "product.Price")
	proto.RegisterType((*Category)(nil), "product.Category")
	proto.RegisterType((*Location)(nil), "product.Location")
	proto.RegisterType((*Schedule)(nil), "product.Schedule")
	proto.RegisterType((*Product)(nil), "product.Product")
	proto.RegisterType((*ListResponse)(nil), "product.ListResponse")
	proto.RegisterType((*CreateRequest)(nil), "product.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "product.CreateResponse")
	proto.RegisterType((*DetailRequest)(nil), "product.DetailRequest")
	proto.RegisterType((*DetailResponse)(nil), "product.DetailResponse")
	proto.RegisterType((*UpdateRequest)(nil), "product.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "product.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "product.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "product.DeleteResponse")
	proto.RegisterType((*SearchRequest)(nil), "product.SearchRequest")
	proto.RegisterType((*SearchParams)(nil), "product.SearchParams")
}

func init() { proto.RegisterFile("product.proto", fileDescriptor_f0fd8b59378f44a5) }

var fileDescriptor_f0fd8b59378f44a5 = []byte{
	// 1015 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcd, 0x6e, 0x1c, 0xc5,
	0x13, 0xd7, 0xee, 0x78, 0x77, 0x67, 0x6b, 0x3f, 0xfe, 0x4e, 0xff, 0x6d, 0xd3, 0x38, 0x82, 0x2c,
	0x03, 0x07, 0x2b, 0x82, 0x04, 0x19, 0x89, 0x1c, 0x08, 0x92, 0x8d, 0x41, 0x3e, 0xc4, 0x42, 0xab,
	0xb1, 0x90, 0x22, 0x2e, 0x56, 0x67, 0xa6, 0xbd, 0x9e, 0x30, 0x33, 0x3d, 0xee, 0xee, 0x8d, 0xd8,
	0x70, 0xe3, 0x09, 0x78, 0x0f, 0xde, 0x84, 0xa7, 0x42, 0x5d, 0xdd, 0x3d, 0x1f, 0x6b, 0x8b, 0xa0,
	0x70, 0xda, 0xae, 0xea, 0xaa, 0xea, 0x5f, 0x55, 0xfd, 0xaa, 0x66, 0x61, 0x56, 0x49, 0x91, 0xae,
	0x13, 0xfd, 0xa4, 0x92, 0x42, 0x0b, 0x32, 0x72, 0x62, 0x34, 0x87, 0x69, 0xcc, 0x6f, 0xd7, 0x5c,
	0xe9, 0x1f, 0x8a, 0x4a, 0x6f, 0xa2, 0x4f, 0x60, 0x72, 0xce, 0x94, 0x96, 0xa2, 0x14, 0x45, 0xc6,
	0x09, 0x81, 0x9d, 0x92, 0x15, 0x9c, 0xf6, 0x16, 0xbd, 0xa3, 0x71, 0x8c, 0xe7, 0xe8, 0x4b, 0x80,
	0x33, 0x21, 0x64, 0x9a, 0x95, 0x4c, 0x73, 0xb2, 0x0b, 0x41, 0x2e, 0x4a, 0x34, 0xe8, 0xc7, 0xe6,
	0x88, 0x1a, 0xa6, 0x69, 0xdf, 0x69, 0x98, 0x8e, 0x3e, 0x85, 0xd9, 0x69, 0x92, 0x88, 0xa2, 0x62,
	0x65, 0x56, 0xf0, 0x52, 0xdf, 0x1b, 0xf6, 0x21, 0x8c, 0x96, 0x59, 0xa2, 0xd7, 0x12, 0x63, 0x2a,
	0x99, 0xb8, 0x5b, 0x73, 0x8c, 0x5e, 0xc0, 0xe8, 0x9c, 0xe5, 0x39, 0x97, 0x1b, 0xe3, 0x5b, 0xb0,
	0xcc, 0xbe, 0x38, 0x88, 0xf1, 0x4c, 0x3e, 0x87, 0xb0, 0xb2, 0xbe, 0x8a, 0xf6, 0x17, 0xc1, 0xd1,
	0xe4, 0x78, 0xf7, 0x89, 0x4f, 0xd8, 0x05, 0x8d, 0x6b, 0x8b, 0xe8, 0x19, 0x0c, 0x96, 0x32, 0x4b,
	0x30, 0xbb, 0x57, 0x4c, 0x59, 0x18, 0x41, 0x8c, 0x67, 0x72, 0x08, 0x61, 0xb2, 0x96, 0x92, 0x97,
	0xc9, 0x06, 0x53, 0x18, 0xc7, 0xb5, 0x1c, 0x7d, 0x0c, 0xe1, 0x19, 0xd3, 0x7c, 0x25, 0x2c, 0x8c,
	0x3b, 0x29, 0xfc, 0x06, 0xe1, 0x85, 0x48, 0x98, 0xce, 0x44, 0x49, 0x28, 0x8c, 0x58, 0x9a, 0x4a,
	0xae, 0x94, 0x33, 0xf1, 0xa2, 0xc9, 0x2e, 0xa9, 0x12, 0x17, 0xdc, 0x1c, 0x4d, 0xac, 0xb7, 0xa2,
	0xe4, 0x34, 0xb0, 0xb1, 0xcc, 0x99, 0x3c, 0x85, 0x30, 0x77, 0xb1, 0xe8, 0xce, 0xa2, 0x77, 0x34,
	0x39, 0xfe, 0x7f, 0x9d, 0x52, 0x53, 0xfe, 0xb8, 0x36, 0x8a, 0x7e, 0xef, 0x41, 0x78, 0x99, 0xdc,
	0xf0, 0x74, 0x9d, 0x63, 0x66, 0x29, 0xd3, 0x35, 0x3a, 0x73, 0x26, 0x1f, 0x42, 0xa8, 0x34, 0x93,
	0xfa, 0x8a, 0x15, 0xee, 0xf1, 0x11, 0xca, 0xa7, 0x05, 0xd9, 0x87, 0x21, 0x2f, 0x53, 0x73, 0x61,
	0x21, 0x0c, 0x78, 0x99, 0x9e, 0x16, 0x8d, 0x47, 0x55, 0x20, 0x06, 0xef, 0xb1, 0xac, 0x3d, 0xaa,
	0x82, 0x0e, 0x6a, 0x8f, 0x65, 0x11, 0xfd, 0x39, 0x80, 0xd1, 0xd2, 0xa2, 0xbc, 0xaf, 0x42, 0x64,
	0x0e, 0xfd, 0x2c, 0x75, 0xaf, 0xf7, 0xb3, 0x94, 0x3c, 0x84, 0x71, 0x95, 0xb3, 0x84, 0x5f, 0x49,
	0x7e, 0xed, 0xde, 0x0e, 0x51, 0x11, 0xf3, 0x6b, 0xf2, 0x11, 0x80, 0xbd, 0xc4, 0x30, 0x16, 0x80,
	0x35, 0xff, 0xd1, 0xc4, 0xaa, 0xaf, 0x73, 0xb1, 0x12, 0x0e, 0x86, 0xbd, 0xbe, 0x10, 0x2b, 0x81,
	0x8d, 0x74, 0xcd, 0xa2, 0x43, 0xd7, 0x48, 0xdf, 0xbc, 0x3d, 0x18, 0x54, 0x86, 0x01, 0x74, 0x84,
	0x24, 0xb2, 0x02, 0x6a, 0x6f, 0x4c, 0x1f, 0x42, 0x9b, 0x12, 0x0a, 0x64, 0x01, 0x93, 0x94, 0xab,
	0x44, 0x66, 0x15, 0xf6, 0x62, 0x8c, 0x77, 0x6d, 0x15, 0xf9, 0x1a, 0x26, 0xab, 0x66, 0x66, 0x28,
	0x20, 0x01, 0xf7, 0xea, 0x6e, 0xb5, 0xe6, 0x29, 0x6e, 0x1b, 0x92, 0x2f, 0x5a, 0x2d, 0x9e, 0x60,
	0x8b, 0x1f, 0xd4, 0x4e, 0x9e, 0x47, 0x4d, 0x83, 0x0d, 0xbc, 0x3c, 0xfb, 0x85, 0x2b, 0x3a, 0x45,
	0xba, 0x5a, 0xc1, 0xf0, 0x4c, 0xf2, 0x24, 0xab, 0xb8, 0xa2, 0xb3, 0x45, 0x60, 0x5a, 0xe4, 0x44,
	0xf2, 0x1c, 0x66, 0xac, 0x3d, 0x75, 0x74, 0x8e, 0xc0, 0x0e, 0xea, 0x37, 0x3a, 0x33, 0x19, 0x77,
	0x8d, 0x4d, 0xf9, 0xd2, 0x4c, 0x25, 0x62, 0x5d, 0x6a, 0xfa, 0x3f, 0xac, 0x52, 0x2d, 0x9b, 0xce,
	0xaa, 0xec, 0x2d, 0xa7, 0xbb, 0xb6, 0xb3, 0xe6, 0x6c, 0xec, 0x6f, 0xd7, 0xac, 0xd4, 0x99, 0xde,
	0xd0, 0x07, 0xd6, 0xde, 0xcb, 0xe4, 0x11, 0x4c, 0x54, 0x95, 0x25, 0x9b, 0xab, 0x9c, 0xbf, 0xe1,
	0x39, 0x25, 0x78, 0x0d, 0xa8, 0xba, 0x30, 0x1a, 0xf2, 0x18, 0x46, 0x2b, 0x3b, 0xde, 0x74, 0x0f,
	0x0b, 0xb1, 0xdb, 0xaa, 0x1e, 0xea, 0x63, 0x6f, 0x60, 0xaa, 0xa6, 0x1c, 0xcd, 0xe9, 0x3e, 0x66,
	0xd4, 0x54, 0xcd, 0xf3, 0x3f, 0xae, 0x4d, 0x0c, 0xae, 0x52, 0x68, 0x5b, 0xe4, 0x03, 0x8b, 0xcb,
	0xcb, 0xd1, 0xaf, 0x30, 0xbd, 0xc8, 0x94, 0x8e, 0xb9, 0xaa, 0x44, 0xa9, 0x38, 0x39, 0x80, 0xa1,
	0xd2, 0x4c, 0xaf, 0x95, 0x5b, 0x2e, 0x4e, 0x32, 0x95, 0xe7, 0x52, 0x0a, 0xe9, 0x88, 0x6b, 0x05,
	0xa3, 0xd5, 0x42, 0xb3, 0x1c, 0x79, 0x1b, 0xc4, 0x56, 0x20, 0x9f, 0xe1, 0xe4, 0x31, 0xba, 0xb3,
	0xbd, 0x86, 0xec, 0x2f, 0xce, 0x22, 0x8b, 0xbe, 0x81, 0xd9, 0x99, 0xe4, 0x66, 0x80, 0xed, 0xf2,
	0x35, 0x15, 0xa8, 0xd8, 0x26, 0x17, 0x2c, 0xc5, 0xb7, 0xef, 0xf3, 0xf4, 0x06, 0xd1, 0x4b, 0x98,
	0x7b, 0xe7, 0x7f, 0x0b, 0x3c, 0x68, 0x03, 0xa7, 0xcd, 0x5b, 0x6e, 0x0f, 0xf8, 0xc8, 0x8f, 0x60,
	0xf6, 0x3d, 0xd7, 0x2c, 0xcb, 0x3d, 0x2c, 0x3b, 0xaf, 0x3b, 0x7e, 0x5e, 0xa3, 0xd7, 0x30, 0xf7,
	0x06, 0xef, 0x55, 0xb3, 0x56, 0x9a, 0x3b, 0xef, 0x4a, 0xf3, 0x05, 0xcc, 0x7e, 0xaa, 0xd2, 0x56,
	0x8d, 0x2c, 0x98, 0x5e, 0xbd, 0x3c, 0x1e, 0x77, 0xf3, 0xf8, 0xc7, 0x60, 0xaf, 0x61, 0xee, 0x83,
	0xfd, 0x57, 0xe0, 0xc1, 0xbb, 0xde, 0xc2, 0x2a, 0xe6, 0x7c, 0x1b, 0x78, 0x50, 0x57, 0xf1, 0xa5,
	0xa9, 0xa2, 0x35, 0x78, 0x2f, 0x30, 0xb4, 0x0b, 0x26, 0x6c, 0x9e, 0x3e, 0x81, 0xd9, 0x25, 0x67,
	0x32, 0xb9, 0xf1, 0x4f, 0x3f, 0xdd, 0xe6, 0xd5, 0x7e, 0x33, 0x2c, 0x68, 0xb8, 0x64, 0x92, 0x15,
	0xaa, 0x89, 0xf0, 0x47, 0x0f, 0xa6, 0xed, 0x1b, 0x32, 0x85, 0xde, 0xad, 0x2b, 0x7a, 0xef, 0xd6,
	0x8c, 0xfe, 0xb5, 0x14, 0xf6, 0x03, 0x32, 0x88, 0xf1, 0x6c, 0xd2, 0xd3, 0x02, 0x91, 0x0c, 0xe2,
	0xbe, 0xc6, 0xcd, 0x6b, 0xf4, 0xf8, 0x01, 0xb2, 0xd4, 0xa9, 0x65, 0x93, 0xa8, 0x16, 0x78, 0x63,
	0x17, 0xb6, 0x93, 0xb6, 0xb6, 0x75, 0xd0, 0xde, 0xd6, 0xc7, 0x7f, 0xf5, 0x61, 0xee, 0x8a, 0x7c,
	0xc9, 0xe5, 0x1b, 0xb3, 0xaa, 0x9f, 0xc1, 0xd0, 0x82, 0x24, 0x07, 0x5b, 0xf9, 0xb8, 0xc4, 0x0f,
	0x9b, 0x3c, 0x3b, 0x23, 0xfe, 0x1c, 0xc6, 0xe7, 0x5c, 0x5b, 0x0e, 0xb7, 0x7c, 0x3b, 0xac, 0x3f,
	0xfc, 0xe0, 0x8e, 0xde, 0x79, 0x7f, 0x0b, 0x70, 0x9a, 0xa6, 0xfe, 0x03, 0xd7, 0xb8, 0x77, 0x66,
	0xb9, 0xe5, 0xbe, 0x35, 0xa6, 0x27, 0x9e, 0xd1, 0x77, 0x23, 0x74, 0x98, 0xde, 0x8a, 0xb0, 0x45,
	0xda, 0x13, 0x4f, 0xad, 0xbb, 0x11, 0x3a, 0x94, 0xeb, 0xa4, 0xd0, 0x66, 0xda, 0x77, 0xe3, 0x9f,
	0xfd, 0x7f, 0xbf, 0x57, 0x43, 0xfc, 0x2f, 0xf8, 0xd5, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x05,
	0x25, 0x36, 0xb7, 0x1c, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*ListResponse, error)
	GetDetail(ctx context.Context, in *DetailRequest, opts ...grpc.CallOption) (*DetailResponse, error)
	AddProduct(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	UpdateProduct(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	DeleteProduct(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type productServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductServiceClient(cc *grpc.ClientConn) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetDetail(ctx context.Context, in *DetailRequest, opts ...grpc.CallOption) (*DetailResponse, error) {
	out := new(DetailResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) AddProduct(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/AddProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateProduct(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/UpdateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteProduct(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/DeleteProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	Search(context.Context, *SearchRequest) (*ListResponse, error)
	GetDetail(context.Context, *DetailRequest) (*DetailResponse, error)
	AddProduct(context.Context, *CreateRequest) (*CreateResponse, error)
	UpdateProduct(context.Context, *UpdateRequest) (*UpdateResponse, error)
	DeleteProduct(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetDetail(ctx, req.(*DetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_AddProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).AddProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/AddProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).AddProduct(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/UpdateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateProduct(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/DeleteProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteProduct(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _ProductService_Search_Handler,
		},
		{
			MethodName: "GetDetail",
			Handler:    _ProductService_GetDetail_Handler,
		},
		{
			MethodName: "AddProduct",
			Handler:    _ProductService_AddProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _ProductService_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _ProductService_DeleteProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
