// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package product

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestEmpty) Reset()         { *m = RequestEmpty{} }
func (m *RequestEmpty) String() string { return proto.CompactTextString(m) }
func (*RequestEmpty) ProtoMessage()    {}
func (*RequestEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

func (m *RequestEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestEmpty.Unmarshal(m, b)
}
func (m *RequestEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestEmpty.Marshal(b, m, deterministic)
}
func (m *RequestEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestEmpty.Merge(m, src)
}
func (m *RequestEmpty) XXX_Size() int {
	return xxx_messageInfo_RequestEmpty.Size(m)
}
func (m *RequestEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_RequestEmpty proto.InternalMessageInfo

type Gastronomie struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gastronomie) Reset()         { *m = Gastronomie{} }
func (m *Gastronomie) String() string { return proto.CompactTextString(m) }
func (*Gastronomie) ProtoMessage()    {}
func (*Gastronomie) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{1}
}

func (m *Gastronomie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gastronomie.Unmarshal(m, b)
}
func (m *Gastronomie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gastronomie.Marshal(b, m, deterministic)
}
func (m *Gastronomie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gastronomie.Merge(m, src)
}
func (m *Gastronomie) XXX_Size() int {
	return xxx_messageInfo_Gastronomie.Size(m)
}
func (m *Gastronomie) XXX_DiscardUnknown() {
	xxx_messageInfo_Gastronomie.DiscardUnknown(m)
}

var xxx_messageInfo_Gastronomie proto.InternalMessageInfo

func (m *Gastronomie) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Coordinate struct {
	Lon                  float32  `protobuf:"fixed32,1,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat                  float32  `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{2}
}

func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (m *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(m, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *Coordinate) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

type Accompaniment struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Accompaniment) Reset()         { *m = Accompaniment{} }
func (m *Accompaniment) String() string { return proto.CompactTextString(m) }
func (*Accompaniment) ProtoMessage()    {}
func (*Accompaniment) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{3}
}

func (m *Accompaniment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Accompaniment.Unmarshal(m, b)
}
func (m *Accompaniment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Accompaniment.Marshal(b, m, deterministic)
}
func (m *Accompaniment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Accompaniment.Merge(m, src)
}
func (m *Accompaniment) XXX_Size() int {
	return xxx_messageInfo_Accompaniment.Size(m)
}
func (m *Accompaniment) XXX_DiscardUnknown() {
	xxx_messageInfo_Accompaniment.DiscardUnknown(m)
}

var xxx_messageInfo_Accompaniment proto.InternalMessageInfo

func (m *Accompaniment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MenuLink struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MenuLink) Reset()         { *m = MenuLink{} }
func (m *MenuLink) String() string { return proto.CompactTextString(m) }
func (*MenuLink) ProtoMessage()    {}
func (*MenuLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{4}
}

func (m *MenuLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuLink.Unmarshal(m, b)
}
func (m *MenuLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuLink.Marshal(b, m, deterministic)
}
func (m *MenuLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuLink.Merge(m, src)
}
func (m *MenuLink) XXX_Size() int {
	return xxx_messageInfo_MenuLink.Size(m)
}
func (m *MenuLink) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuLink.DiscardUnknown(m)
}

var xxx_messageInfo_MenuLink proto.InternalMessageInfo

func (m *MenuLink) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Picture struct {
	Src                  string   `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Picture) Reset()         { *m = Picture{} }
func (m *Picture) String() string { return proto.CompactTextString(m) }
func (*Picture) ProtoMessage()    {}
func (*Picture) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{5}
}

func (m *Picture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Picture.Unmarshal(m, b)
}
func (m *Picture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Picture.Marshal(b, m, deterministic)
}
func (m *Picture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Picture.Merge(m, src)
}
func (m *Picture) XXX_Size() int {
	return xxx_messageInfo_Picture.Size(m)
}
func (m *Picture) XXX_DiscardUnknown() {
	xxx_messageInfo_Picture.DiscardUnknown(m)
}

var xxx_messageInfo_Picture proto.InternalMessageInfo

func (m *Picture) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

type Schedule struct {
	Date                 string   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	StartAm              string   `protobuf:"bytes,2,opt,name=start_am,json=startAm,proto3" json:"start_am,omitempty"`
	EndAm                string   `protobuf:"bytes,3,opt,name=end_am,json=endAm,proto3" json:"end_am,omitempty"`
	StartPm              string   `protobuf:"bytes,4,opt,name=start_pm,json=startPm,proto3" json:"start_pm,omitempty"`
	EndPm                string   `protobuf:"bytes,5,opt,name=end_pm,json=endPm,proto3" json:"end_pm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Schedule) Reset()         { *m = Schedule{} }
func (m *Schedule) String() string { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()    {}
func (*Schedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{6}
}

func (m *Schedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schedule.Unmarshal(m, b)
}
func (m *Schedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schedule.Marshal(b, m, deterministic)
}
func (m *Schedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schedule.Merge(m, src)
}
func (m *Schedule) XXX_Size() int {
	return xxx_messageInfo_Schedule.Size(m)
}
func (m *Schedule) XXX_DiscardUnknown() {
	xxx_messageInfo_Schedule.DiscardUnknown(m)
}

var xxx_messageInfo_Schedule proto.InternalMessageInfo

func (m *Schedule) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Schedule) GetStartAm() string {
	if m != nil {
		return m.StartAm
	}
	return ""
}

func (m *Schedule) GetEndAm() string {
	if m != nil {
		return m.EndAm
	}
	return ""
}

func (m *Schedule) GetStartPm() string {
	if m != nil {
		return m.StartPm
	}
	return ""
}

func (m *Schedule) GetEndPm() string {
	if m != nil {
		return m.EndPm
	}
	return ""
}

type Product struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PlaceLogo            string           `protobuf:"bytes,2,opt,name=place_logo,json=placeLogo,proto3" json:"place_logo,omitempty"`
	Price                int32            `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Phone                string           `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Description          string           `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Gastronomie          []*Gastronomie   `protobuf:"bytes,6,rep,name=gastronomie,proto3" json:"gastronomie,omitempty"`
	CookingTime          int32            `protobuf:"varint,7,opt,name=cooking_time,json=cookingTime,proto3" json:"cooking_time,omitempty"`
	Location             *Coordinate      `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	Address              string           `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	Cpc                  string           `protobuf:"bytes,10,opt,name=cpc,proto3" json:"cpc,omitempty"`
	Like                 int32            `protobuf:"varint,11,opt,name=like,proto3" json:"like,omitempty"`
	Recipes              []string         `protobuf:"bytes,12,rep,name=recipes,proto3" json:"recipes,omitempty"`
	Accompaniment        []*Accompaniment `protobuf:"bytes,13,rep,name=accompaniment,proto3" json:"accompaniment,omitempty"`
	PlaceName            string           `protobuf:"bytes,14,opt,name=place_name,json=placeName,proto3" json:"place_name,omitempty"`
	PlaceRef             string           `protobuf:"bytes,15,opt,name=place_ref,json=placeRef,proto3" json:"place_ref,omitempty"`
	MenusLink            *MenuLink        `protobuf:"bytes,16,opt,name=menus_link,json=menusLink,proto3" json:"menus_link,omitempty"`
	Notation             int32            `protobuf:"varint,17,opt,name=notation,proto3" json:"notation,omitempty"`
	Discount             int32            `protobuf:"varint,18,opt,name=discount,proto3" json:"discount,omitempty"`
	Size                 string           `protobuf:"bytes,19,opt,name=size,proto3" json:"size,omitempty"`
	Quantity             int32            `protobuf:"varint,20,opt,name=quantity,proto3" json:"quantity,omitempty"`
	SpicyLevel           int32            `protobuf:"varint,21,opt,name=spicy_level,json=spicyLevel,proto3" json:"spicy_level,omitempty"`
	Category             string           `protobuf:"bytes,22,opt,name=category,proto3" json:"category,omitempty"`
	Picture              []*Picture       `protobuf:"bytes,23,rep,name=picture,proto3" json:"picture,omitempty"`
	MainPicture          int32            `protobuf:"varint,24,opt,name=main_picture,json=mainPicture,proto3" json:"main_picture,omitempty"`
	Schedule             []*Schedule      `protobuf:"bytes,25,rep,name=schedule,proto3" json:"schedule,omitempty"`
	Id                   string           `protobuf:"bytes,26,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{7}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetPlaceLogo() string {
	if m != nil {
		return m.PlaceLogo
	}
	return ""
}

func (m *Product) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetGastronomie() []*Gastronomie {
	if m != nil {
		return m.Gastronomie
	}
	return nil
}

func (m *Product) GetCookingTime() int32 {
	if m != nil {
		return m.CookingTime
	}
	return 0
}

func (m *Product) GetLocation() *Coordinate {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Product) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Product) GetCpc() string {
	if m != nil {
		return m.Cpc
	}
	return ""
}

func (m *Product) GetLike() int32 {
	if m != nil {
		return m.Like
	}
	return 0
}

func (m *Product) GetRecipes() []string {
	if m != nil {
		return m.Recipes
	}
	return nil
}

func (m *Product) GetAccompaniment() []*Accompaniment {
	if m != nil {
		return m.Accompaniment
	}
	return nil
}

func (m *Product) GetPlaceName() string {
	if m != nil {
		return m.PlaceName
	}
	return ""
}

func (m *Product) GetPlaceRef() string {
	if m != nil {
		return m.PlaceRef
	}
	return ""
}

func (m *Product) GetMenusLink() *MenuLink {
	if m != nil {
		return m.MenusLink
	}
	return nil
}

func (m *Product) GetNotation() int32 {
	if m != nil {
		return m.Notation
	}
	return 0
}

func (m *Product) GetDiscount() int32 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *Product) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *Product) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Product) GetSpicyLevel() int32 {
	if m != nil {
		return m.SpicyLevel
	}
	return 0
}

func (m *Product) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Product) GetPicture() []*Picture {
	if m != nil {
		return m.Picture
	}
	return nil
}

func (m *Product) GetMainPicture() int32 {
	if m != nil {
		return m.MainPicture
	}
	return 0
}

func (m *Product) GetSchedule() []*Schedule {
	if m != nil {
		return m.Schedule
	}
	return nil
}

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ProductAPIResponse struct {
	Total                int64      `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*Product `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProductAPIResponse) Reset()         { *m = ProductAPIResponse{} }
func (m *ProductAPIResponse) String() string { return proto.CompactTextString(m) }
func (*ProductAPIResponse) ProtoMessage()    {}
func (*ProductAPIResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{8}
}

func (m *ProductAPIResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductAPIResponse.Unmarshal(m, b)
}
func (m *ProductAPIResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductAPIResponse.Marshal(b, m, deterministic)
}
func (m *ProductAPIResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductAPIResponse.Merge(m, src)
}
func (m *ProductAPIResponse) XXX_Size() int {
	return xxx_messageInfo_ProductAPIResponse.Size(m)
}
func (m *ProductAPIResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductAPIResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductAPIResponse proto.InternalMessageInfo

func (m *ProductAPIResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ProductAPIResponse) GetData() []*Product {
	if m != nil {
		return m.Data
	}
	return nil
}

type ID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{9}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{10}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestEmpty)(nil), "product.RequestEmpty")
	proto.RegisterType((*Gastronomie)(nil), "product.Gastronomie")
	proto.RegisterType((*Coordinate)(nil), "product.Coordinate")
	proto.RegisterType((*Accompaniment)(nil), "product.Accompaniment")
	proto.RegisterType((*MenuLink)(nil), "product.MenuLink")
	proto.RegisterType((*Picture)(nil), "product.Picture")
	proto.RegisterType((*Schedule)(nil), "product.Schedule")
	proto.RegisterType((*Product)(nil), "product.Product")
	proto.RegisterType((*ProductAPIResponse)(nil), "product.ProductAPIResponse")
	proto.RegisterType((*ID)(nil), "product.ID")
	proto.RegisterType((*DeleteResponse)(nil), "product.DeleteResponse")
}

func init() { proto.RegisterFile("product.proto", fileDescriptor_f0fd8b59378f44a5) }

var fileDescriptor_f0fd8b59378f44a5 = []byte{
	// 780 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x55, 0xcd, 0x6e, 0x1b, 0x37,
	0x10, 0x86, 0xa4, 0x58, 0x3f, 0xb3, 0x96, 0xea, 0x30, 0x76, 0xc2, 0xc8, 0x28, 0xaa, 0xa8, 0x3d,
	0x18, 0x2d, 0x9a, 0x06, 0x0e, 0xda, 0x53, 0x2e, 0x6a, 0x5d, 0x04, 0x06, 0xdc, 0x42, 0xd8, 0xb4,
	0x97, 0x5e, 0x04, 0x96, 0x3b, 0x51, 0x08, 0xef, 0x92, 0xcc, 0x92, 0x0a, 0xe0, 0x1e, 0xfb, 0x82,
	0x7d, 0x8c, 0xbe, 0x46, 0xc1, 0x21, 0x77, 0xb5, 0xfe, 0xe9, 0x69, 0x67, 0xbe, 0x99, 0x21, 0xe7,
	0xef, 0xe3, 0xc2, 0xd4, 0xd6, 0xa6, 0xd8, 0x49, 0xff, 0xd2, 0xd6, 0xc6, 0x1b, 0x36, 0x4a, 0xea,
	0x72, 0x06, 0x87, 0x39, 0x7e, 0xdc, 0xa1, 0xf3, 0x3f, 0x57, 0xd6, 0xdf, 0x2c, 0x5f, 0x40, 0xf6,
	0x56, 0x38, 0x5f, 0x1b, 0x6d, 0x2a, 0x85, 0x8c, 0xc1, 0x23, 0x2d, 0x2a, 0xe4, 0xbd, 0x45, 0xef,
	0x6c, 0x92, 0x93, 0xbc, 0x7c, 0x05, 0xf0, 0x93, 0x31, 0x75, 0xa1, 0xb4, 0xf0, 0xc8, 0x8e, 0x60,
	0x50, 0x1a, 0x4d, 0x0e, 0xfd, 0x3c, 0x88, 0x84, 0x08, 0xcf, 0xfb, 0x09, 0x11, 0x7e, 0xf9, 0x25,
	0x4c, 0x57, 0x52, 0x9a, 0xca, 0x0a, 0xad, 0x2a, 0xd4, 0xfe, 0xc1, 0x63, 0xe7, 0x30, 0xfe, 0x05,
	0xf5, 0xee, 0x4a, 0xe9, 0x6b, 0x36, 0x83, 0xbe, 0x2a, 0x92, 0xb5, 0xaf, 0x8a, 0xe5, 0x29, 0x8c,
	0xd6, 0x4a, 0xfa, 0x5d, 0x4d, 0xf7, 0xb9, 0x5a, 0x26, 0x5b, 0x10, 0x97, 0x7f, 0xf7, 0x60, 0xfc,
	0x4e, 0x7e, 0xc0, 0x62, 0x57, 0x52, 0xc2, 0x85, 0xf0, 0xed, 0xc9, 0x41, 0x66, 0xcf, 0x61, 0xec,
	0xbc, 0xa8, 0xfd, 0x46, 0x54, 0x94, 0xd5, 0x24, 0x1f, 0x91, 0xbe, 0xaa, 0xd8, 0x09, 0x0c, 0x51,
	0x17, 0xc1, 0x30, 0x20, 0xc3, 0x01, 0xea, 0x62, 0x55, 0xed, 0x23, 0x6c, 0xc5, 0x1f, 0x75, 0x22,
	0xd6, 0x6d, 0x84, 0xad, 0xf8, 0x41, 0x1b, 0xb1, 0xae, 0x96, 0xff, 0x0c, 0x61, 0xb4, 0x8e, 0x3d,
	0x7d, 0xa8, 0x3a, 0xf6, 0x39, 0x80, 0x2d, 0x85, 0xc4, 0x4d, 0x69, 0xb6, 0x26, 0x65, 0x31, 0x21,
	0xe4, 0xca, 0x6c, 0x0d, 0x3b, 0x86, 0x03, 0x5b, 0x2b, 0x89, 0x94, 0xc6, 0x41, 0x1e, 0x15, 0x42,
	0x3f, 0x18, 0x8d, 0x29, 0x87, 0xa8, 0xb0, 0x05, 0x64, 0x05, 0x3a, 0x59, 0x2b, 0xeb, 0x95, 0xd1,
	0x29, 0x8d, 0x2e, 0xc4, 0x7e, 0x80, 0x6c, 0xbb, 0x1f, 0x22, 0x1f, 0x2e, 0x06, 0x67, 0xd9, 0xf9,
	0xf1, 0xcb, 0x66, 0x05, 0x3a, 0x03, 0xce, 0xbb, 0x8e, 0xec, 0x05, 0x1c, 0x4a, 0x63, 0xae, 0x95,
	0xde, 0x6e, 0xbc, 0xaa, 0x90, 0x8f, 0x28, 0x99, 0x2c, 0x61, 0xbf, 0xa9, 0x0a, 0xd9, 0x77, 0x30,
	0x2e, 0x8d, 0x14, 0x74, 0xf3, 0x78, 0xd1, 0x3b, 0xcb, 0xce, 0x9f, 0xb4, 0xe7, 0xee, 0xb7, 0x22,
	0x6f, 0x9d, 0x18, 0x87, 0x91, 0x28, 0x8a, 0x1a, 0x9d, 0xe3, 0x93, 0xd8, 0xc9, 0xa4, 0x86, 0x49,
	0x4a, 0x2b, 0x39, 0xc4, 0x49, 0x4a, 0x2b, 0x43, 0xe3, 0x4a, 0x75, 0x8d, 0x3c, 0xa3, 0x7b, 0x49,
	0x0e, 0xf1, 0x35, 0x4a, 0x65, 0xd1, 0xf1, 0xc3, 0xc5, 0x20, 0xc4, 0x27, 0x95, 0xbd, 0x81, 0xa9,
	0xe8, 0x6e, 0x15, 0x9f, 0x52, 0x9d, 0x4f, 0xdb, 0x7c, 0x6e, 0xed, 0x5c, 0x7e, 0xdb, 0x79, 0x3f,
	0x10, 0x1a, 0xd5, 0xac, 0x33, 0x90, 0x5f, 0xc3, 0xbc, 0x4e, 0x21, 0x2a, 0x9b, 0x1a, 0xdf, 0xf3,
	0xcf, 0xc8, 0x3a, 0x26, 0x20, 0xc7, 0xf7, 0xec, 0x15, 0x40, 0x85, 0x7a, 0xe7, 0x36, 0xa5, 0xd2,
	0xd7, 0xfc, 0x88, 0xda, 0xf0, 0xb8, 0xbd, 0xb6, 0xd9, 0xe2, 0x7c, 0x42, 0x4e, 0xb4, 0xd0, 0x73,
	0x18, 0x6b, 0xe3, 0x63, 0xdb, 0x1e, 0x53, 0x75, 0xad, 0x1e, 0x6c, 0x85, 0x72, 0xd2, 0xec, 0xb4,
	0xe7, 0x2c, 0xda, 0x1a, 0x3d, 0x74, 0xc4, 0xa9, 0xbf, 0x90, 0x3f, 0x89, 0xab, 0x14, 0xe4, 0xe0,
	0xff, 0x71, 0x27, 0xb4, 0x57, 0xfe, 0x86, 0x1f, 0x47, 0xff, 0x46, 0x67, 0x5f, 0x40, 0xe6, 0xac,
	0x92, 0x37, 0x9b, 0x12, 0x3f, 0x61, 0xc9, 0x4f, 0xc8, 0x0c, 0x04, 0x5d, 0x05, 0x24, 0x04, 0x4b,
	0xe1, 0x71, 0x6b, 0xea, 0x1b, 0xfe, 0x34, 0x96, 0xd5, 0xe8, 0xec, 0x6b, 0x18, 0xd9, 0xc8, 0x32,
	0xfe, 0x8c, 0x5a, 0x79, 0xd4, 0xd6, 0x94, 0xd8, 0x97, 0x37, 0x0e, 0x61, 0x55, 0x2a, 0xa1, 0xf4,
	0xa6, 0x09, 0xe0, 0x71, 0x55, 0x02, 0xd6, 0x30, 0xf5, 0x5b, 0x18, 0xbb, 0x44, 0x4b, 0xfe, 0x9c,
	0xce, 0xdb, 0xf7, 0xa8, 0xe1, 0x6b, 0xde, 0xba, 0x24, 0xce, 0xcf, 0x5b, 0xce, 0xaf, 0x81, 0x25,
	0x42, 0xad, 0xd6, 0x97, 0x39, 0x3a, 0x6b, 0xb4, 0x23, 0x4a, 0x78, 0xe3, 0x45, 0x49, 0xe4, 0x1a,
	0xe4, 0x51, 0x61, 0x5f, 0x11, 0xeb, 0x05, 0xef, 0xdf, 0x4d, 0x3b, 0x7e, 0xe9, 0x1d, 0x10, 0xcb,
	0x63, 0xe8, 0x5f, 0x5e, 0xdc, 0x7b, 0x5b, 0xce, 0x61, 0x76, 0x81, 0x25, 0x7a, 0x6c, 0xef, 0xb8,
	0xe3, 0x11, 0x16, 0xb5, 0x72, 0xdb, 0x44, 0xda, 0x20, 0x9e, 0xff, 0xdb, 0x83, 0x59, 0x3a, 0xfb,
	0x1d, 0xd6, 0x9f, 0x02, 0x57, 0xdf, 0xc0, 0xf0, 0x2d, 0xfa, 0x55, 0x59, 0xb2, 0x93, 0xf6, 0xfa,
	0xee, 0xcb, 0x3a, 0x3f, 0xbd, 0x9b, 0x55, 0xb7, 0xac, 0x6f, 0x00, 0x56, 0x45, 0xd1, 0x3c, 0x20,
	0xf7, 0x0a, 0x98, 0x67, 0x2d, 0x72, 0x79, 0xc1, 0x5e, 0xc3, 0xf4, 0x77, 0x1b, 0x5e, 0xb6, 0xff,
	0xf7, 0xbf, 0x87, 0xb0, 0xef, 0x61, 0x1a, 0xcb, 0x6c, 0x80, 0xee, 0x91, 0xf3, 0x67, 0xad, 0x72,
	0xbb, 0x17, 0x3f, 0x4e, 0xfe, 0x68, 0x7e, 0x15, 0x7f, 0x0e, 0xe9, 0xd7, 0xf1, 0xfa, 0xbf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xab, 0x44, 0xea, 0x6c, 0x4b, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	GetAll(ctx context.Context, in *RequestEmpty, opts ...grpc.CallOption) (*ProductAPIResponse, error)
	AddProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*ID, error)
	UpdateProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*Product, error)
	DeleteProduct(ctx context.Context, in *ID, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type productServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductServiceClient(cc *grpc.ClientConn) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) GetAll(ctx context.Context, in *RequestEmpty, opts ...grpc.CallOption) (*ProductAPIResponse, error) {
	out := new(ProductAPIResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) AddProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*ID, error) {
	out := new(ID)
	err := c.cc.Invoke(ctx, "/product.ProductService/AddProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/product.ProductService/UpdateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteProduct(ctx context.Context, in *ID, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/DeleteProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	GetAll(context.Context, *RequestEmpty) (*ProductAPIResponse, error)
	AddProduct(context.Context, *Product) (*ID, error)
	UpdateProduct(context.Context, *Product) (*Product, error)
	DeleteProduct(context.Context, *ID) (*DeleteResponse, error)
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetAll(ctx, req.(*RequestEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_AddProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Product)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).AddProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/AddProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).AddProduct(ctx, req.(*Product))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Product)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/UpdateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateProduct(ctx, req.(*Product))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/DeleteProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteProduct(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _ProductService_GetAll_Handler,
		},
		{
			MethodName: "AddProduct",
			Handler:    _ProductService_AddProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _ProductService_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _ProductService_DeleteProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
