// Code generated by protoc-gen-go. DO NOT EDIT.
// source: place.store.proto

package place

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Coordinate struct {
	Lon                  float32  `protobuf:"fixed32,1,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat                  float32  `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_161d5f758bceed95, []int{0}
}

func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (m *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(m, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *Coordinate) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

type Picture struct {
	Src                  string   `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Picture) Reset()         { *m = Picture{} }
func (m *Picture) String() string { return proto.CompactTextString(m) }
func (*Picture) ProtoMessage()    {}
func (*Picture) Descriptor() ([]byte, []int) {
	return fileDescriptor_161d5f758bceed95, []int{1}
}

func (m *Picture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Picture.Unmarshal(m, b)
}
func (m *Picture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Picture.Marshal(b, m, deterministic)
}
func (m *Picture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Picture.Merge(m, src)
}
func (m *Picture) XXX_Size() int {
	return xxx_messageInfo_Picture.Size(m)
}
func (m *Picture) XXX_DiscardUnknown() {
	xxx_messageInfo_Picture.DiscardUnknown(m)
}

var xxx_messageInfo_Picture proto.InternalMessageInfo

func (m *Picture) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price                int32    `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Like                 int32    `protobuf:"varint,5,opt,name=like,proto3" json:"like,omitempty"`
	Recipes              []string `protobuf:"bytes,6,rep,name=recipes,proto3" json:"recipes,omitempty"`
	Notation             int32    `protobuf:"varint,7,opt,name=notation,proto3" json:"notation,omitempty"`
	Discount             int32    `protobuf:"varint,8,opt,name=discount,proto3" json:"discount,omitempty"`
	Picture              string   `protobuf:"bytes,9,opt,name=picture,proto3" json:"picture,omitempty"`
	Size                 string   `protobuf:"bytes,10,opt,name=size,proto3" json:"size,omitempty"`
	Position             int32    `protobuf:"varint,11,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_161d5f758bceed95, []int{2}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetLike() int32 {
	if m != nil {
		return m.Like
	}
	return 0
}

func (m *Product) GetRecipes() []string {
	if m != nil {
		return m.Recipes
	}
	return nil
}

func (m *Product) GetNotation() int32 {
	if m != nil {
		return m.Notation
	}
	return 0
}

func (m *Product) GetDiscount() int32 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *Product) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *Product) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *Product) GetPosition() int32 {
	if m != nil {
		return m.Position
	}
	return 0
}

type PlaceStore struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CategoryCode         string     `protobuf:"bytes,3,opt,name=category_code,json=categoryCode,proto3" json:"category_code,omitempty"`
	CategoryName         string     `protobuf:"bytes,4,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	PlaceId              string     `protobuf:"bytes,5,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	Collection           []*Product `protobuf:"bytes,6,rep,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PlaceStore) Reset()         { *m = PlaceStore{} }
func (m *PlaceStore) String() string { return proto.CompactTextString(m) }
func (*PlaceStore) ProtoMessage()    {}
func (*PlaceStore) Descriptor() ([]byte, []int) {
	return fileDescriptor_161d5f758bceed95, []int{3}
}

func (m *PlaceStore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceStore.Unmarshal(m, b)
}
func (m *PlaceStore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceStore.Marshal(b, m, deterministic)
}
func (m *PlaceStore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceStore.Merge(m, src)
}
func (m *PlaceStore) XXX_Size() int {
	return xxx_messageInfo_PlaceStore.Size(m)
}
func (m *PlaceStore) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceStore.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceStore proto.InternalMessageInfo

func (m *PlaceStore) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PlaceStore) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlaceStore) GetCategoryCode() string {
	if m != nil {
		return m.CategoryCode
	}
	return ""
}

func (m *PlaceStore) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

func (m *PlaceStore) GetPlaceId() string {
	if m != nil {
		return m.PlaceId
	}
	return ""
}

func (m *PlaceStore) GetCollection() []*Product {
	if m != nil {
		return m.Collection
	}
	return nil
}

type Gastronomie struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gastronomie) Reset()         { *m = Gastronomie{} }
func (m *Gastronomie) String() string { return proto.CompactTextString(m) }
func (*Gastronomie) ProtoMessage()    {}
func (*Gastronomie) Descriptor() ([]byte, []int) {
	return fileDescriptor_161d5f758bceed95, []int{4}
}

func (m *Gastronomie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gastronomie.Unmarshal(m, b)
}
func (m *Gastronomie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gastronomie.Marshal(b, m, deterministic)
}
func (m *Gastronomie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gastronomie.Merge(m, src)
}
func (m *Gastronomie) XXX_Size() int {
	return xxx_messageInfo_Gastronomie.Size(m)
}
func (m *Gastronomie) XXX_DiscardUnknown() {
	xxx_messageInfo_Gastronomie.DiscardUnknown(m)
}

var xxx_messageInfo_Gastronomie proto.InternalMessageInfo

func (m *Gastronomie) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_161d5f758bceed95, []int{5}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_161d5f758bceed95, []int{6}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DeleteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DeleteResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_161d5f758bceed95, []int{7}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UpdateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DetailResponse struct {
	Status               int32       `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *PlaceStore `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DetailResponse) Reset()         { *m = DetailResponse{} }
func (m *DetailResponse) String() string { return proto.CompactTextString(m) }
func (*DetailResponse) ProtoMessage()    {}
func (*DetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_161d5f758bceed95, []int{8}
}

func (m *DetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailResponse.Unmarshal(m, b)
}
func (m *DetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailResponse.Marshal(b, m, deterministic)
}
func (m *DetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailResponse.Merge(m, src)
}
func (m *DetailResponse) XXX_Size() int {
	return xxx_messageInfo_DetailResponse.Size(m)
}
func (m *DetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetailResponse proto.InternalMessageInfo

func (m *DetailResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DetailResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DetailResponse) GetData() *PlaceStore {
	if m != nil {
		return m.Data
	}
	return nil
}

type SearchRequest struct {
	Q                    string   `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	From                 int32    `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   int32    `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_161d5f758bceed95, []int{9}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *SearchRequest) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *SearchRequest) GetTo() int32 {
	if m != nil {
		return m.To
	}
	return 0
}

type ListResponse struct {
	Status               int32         `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Total                int64         `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*PlaceStore `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_161d5f758bceed95, []int{10}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ListResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListResponse) GetData() []*PlaceStore {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_161d5f758bceed95, []int{11}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type FoodCategory struct {
	CategoryName         string   `protobuf:"bytes,1,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	CategoryCode         string   `protobuf:"bytes,2,opt,name=category_code,json=categoryCode,proto3" json:"category_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FoodCategory) Reset()         { *m = FoodCategory{} }
func (m *FoodCategory) String() string { return proto.CompactTextString(m) }
func (*FoodCategory) ProtoMessage()    {}
func (*FoodCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_161d5f758bceed95, []int{12}
}

func (m *FoodCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodCategory.Unmarshal(m, b)
}
func (m *FoodCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodCategory.Marshal(b, m, deterministic)
}
func (m *FoodCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodCategory.Merge(m, src)
}
func (m *FoodCategory) XXX_Size() int {
	return xxx_messageInfo_FoodCategory.Size(m)
}
func (m *FoodCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodCategory.DiscardUnknown(m)
}

var xxx_messageInfo_FoodCategory proto.InternalMessageInfo

func (m *FoodCategory) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

func (m *FoodCategory) GetCategoryCode() string {
	if m != nil {
		return m.CategoryCode
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_161d5f758bceed95, []int{13}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Coordinate)(nil), "place.Coordinate")
	proto.RegisterType((*Picture)(nil), "place.Picture")
	proto.RegisterType((*Product)(nil), "place.Product")
	proto.RegisterType((*PlaceStore)(nil), "place.PlaceStore")
	proto.RegisterType((*Gastronomie)(nil), "place.Gastronomie")
	proto.RegisterType((*ID)(nil), "place.ID")
	proto.RegisterType((*DeleteResponse)(nil), "place.DeleteResponse")
	proto.RegisterType((*UpdateResponse)(nil), "place.UpdateResponse")
	proto.RegisterType((*DetailResponse)(nil), "place.DetailResponse")
	proto.RegisterType((*SearchRequest)(nil), "place.SearchRequest")
	proto.RegisterType((*ListResponse)(nil), "place.ListResponse")
	proto.RegisterType((*CreateResponse)(nil), "place.CreateResponse")
	proto.RegisterType((*FoodCategory)(nil), "place.FoodCategory")
	proto.RegisterType((*Empty)(nil), "place.Empty")
}

func init() { proto.RegisterFile("place.store.proto", fileDescriptor_161d5f758bceed95) }

var fileDescriptor_161d5f758bceed95 = []byte{
	// 638 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x61, 0x6b, 0x13, 0x4d,
	0x10, 0xe6, 0xee, 0x72, 0x49, 0x33, 0x49, 0xc3, 0xdb, 0x7d, 0xab, 0x9c, 0xf5, 0x4b, 0x3d, 0x11,
	0x8b, 0x48, 0x94, 0xf8, 0x0b, 0x6a, 0xaa, 0xa5, 0x20, 0xa5, 0x6c, 0x11, 0xc4, 0x2f, 0x65, 0xbd,
	0x1d, 0x75, 0xf1, 0x72, 0x7b, 0xdd, 0x9d, 0x08, 0xf1, 0x0f, 0xf8, 0xcb, 0xfc, 0x55, 0x7e, 0x91,
	0xdd, 0xbd, 0x4b, 0xd3, 0xa4, 0x14, 0x29, 0x7e, 0x9b, 0x67, 0x76, 0xee, 0xb9, 0x67, 0x9e, 0x99,
	0x5d, 0xd8, 0xa9, 0x4b, 0x51, 0xe0, 0xd8, 0x92, 0x36, 0x38, 0xae, 0x8d, 0x26, 0xcd, 0x52, 0x9f,
	0xca, 0x5f, 0x02, 0x4c, 0xb5, 0x36, 0x52, 0x55, 0x82, 0x90, 0xfd, 0x07, 0x49, 0xa9, 0xab, 0x2c,
	0xda, 0x8f, 0x0e, 0x62, 0xee, 0x42, 0x9f, 0x11, 0x94, 0xc5, 0x4d, 0x46, 0x50, 0xfe, 0x10, 0x7a,
	0x67, 0xaa, 0xa0, 0xb9, 0xf1, 0xe5, 0xd6, 0x14, 0xbe, 0xbc, 0xcf, 0x5d, 0x98, 0xff, 0x8c, 0xa1,
	0x77, 0x66, 0xb4, 0x9c, 0x17, 0xc4, 0x46, 0x10, 0x2b, 0xd9, 0x1c, 0xc6, 0x4a, 0x32, 0x06, 0x1d,
	0x5a, 0xd4, 0xe8, 0xb9, 0xfa, 0xdc, 0xc7, 0x2e, 0x57, 0x89, 0x19, 0x66, 0x49, 0xc8, 0xb9, 0x98,
	0xed, 0x42, 0x5a, 0x1b, 0x55, 0x60, 0xd6, 0xd9, 0x8f, 0x0e, 0x52, 0x1e, 0x80, 0xab, 0x2c, 0xd5,
	0x37, 0xcc, 0x52, 0x9f, 0xf4, 0x31, 0xcb, 0xa0, 0x67, 0xb0, 0x50, 0x35, 0xda, 0xac, 0xbb, 0x9f,
	0x1c, 0xf4, 0x79, 0x0b, 0xd9, 0x1e, 0x6c, 0x55, 0x9a, 0x04, 0x29, 0x5d, 0x65, 0x3d, 0xff, 0xc5,
	0x12, 0xbb, 0x33, 0xa9, 0x6c, 0xa1, 0xe7, 0x15, 0x65, 0x5b, 0xe1, 0xac, 0xc5, 0x8e, 0xb1, 0x0e,
	0xcd, 0x65, 0x7d, 0x2f, 0xa9, 0x85, 0xee, 0xff, 0x56, 0xfd, 0xc0, 0x0c, 0x82, 0x52, 0x17, 0x3b,
	0xa6, 0x5a, 0x5b, 0xe5, 0xff, 0x32, 0x08, 0x4c, 0x2d, 0xce, 0x7f, 0x45, 0x00, 0x67, 0xce, 0xe2,
	0x73, 0x67, 0xfa, 0x4d, 0x66, 0xf8, 0xc6, 0xe3, 0x95, 0xc6, 0x1f, 0xc3, 0x76, 0x21, 0x08, 0xbf,
	0x68, 0xb3, 0xb8, 0x28, 0xb4, 0x6c, 0x5d, 0x19, 0xb6, 0xc9, 0xa9, 0x96, 0xd7, 0x8b, 0x3c, 0x43,
	0xe7, 0x7a, 0xd1, 0xa9, 0x63, 0x7a, 0x00, 0x5b, 0x7e, 0xbc, 0x17, 0x4a, 0x7a, 0xc3, 0x5c, 0x1f,
	0x0e, 0x9f, 0x48, 0x36, 0x06, 0x28, 0x74, 0x59, 0x62, 0xe1, 0x55, 0x3b, 0xdb, 0x06, 0x93, 0xd1,
	0x38, 0xec, 0x47, 0x33, 0x39, 0xbe, 0x52, 0x91, 0x3f, 0x82, 0xc1, 0xb1, 0xb0, 0x64, 0x74, 0xa5,
	0x67, 0xea, 0x6a, 0x60, 0xd1, 0x95, 0xee, 0x7c, 0x17, 0xe2, 0x93, 0xa3, 0xf5, 0x0e, 0xf3, 0x53,
	0x18, 0x1d, 0x61, 0x89, 0x84, 0x1c, 0x6d, 0xad, 0x2b, 0x8b, 0xec, 0x3e, 0x74, 0x2d, 0x09, 0x9a,
	0x5b, 0x5f, 0x95, 0xf2, 0x06, 0xb9, 0x81, 0xa3, 0x31, 0xda, 0x34, 0x66, 0x04, 0xd0, 0xf0, 0x25,
	0xab, 0x7c, 0xef, 0x6b, 0x29, 0xfe, 0x19, 0x1f, 0x3a, 0x7d, 0x24, 0x54, 0x79, 0x47, 0xbe, 0x27,
	0xd0, 0x91, 0x82, 0x84, 0xf7, 0x7f, 0x30, 0xd9, 0x69, 0x2d, 0x5c, 0x8e, 0x9c, 0xfb, 0xe3, 0xfc,
	0x10, 0xb6, 0xcf, 0x51, 0x98, 0xe2, 0x2b, 0xc7, 0xcb, 0x39, 0x5a, 0x62, 0x43, 0x88, 0x2e, 0x1b,
	0x9b, 0xa2, 0x4b, 0xe7, 0xe7, 0x67, 0xa3, 0x67, 0x9e, 0x3a, 0xe5, 0x3e, 0x76, 0x4a, 0x49, 0x7b,
	0xa5, 0x29, 0x8f, 0x49, 0xe7, 0x0b, 0x18, 0xbe, 0x53, 0x96, 0xee, 0xa8, 0x73, 0x17, 0x52, 0xd2,
	0x24, 0x4a, 0x4f, 0x98, 0xf0, 0x00, 0x56, 0xd4, 0x27, 0xb7, 0xa9, 0x3f, 0x85, 0xd1, 0xd4, 0xe0,
	0xdf, 0x98, 0x1e, 0xec, 0x8d, 0x97, 0x0b, 0xbe, 0x14, 0x93, 0xac, 0x88, 0xc9, 0x3f, 0xc0, 0xf0,
	0xad, 0xd6, 0x72, 0xda, 0x2c, 0xeb, 0xe6, 0x36, 0x47, 0x37, 0x6c, 0xf3, 0xc6, 0xbd, 0x88, 0x37,
	0xef, 0x45, 0xde, 0x83, 0xf4, 0xcd, 0xac, 0xa6, 0xc5, 0xe4, 0x77, 0x04, 0x3b, 0x57, 0x7d, 0x9c,
	0xa3, 0xf9, 0xee, 0x9e, 0x8f, 0xe7, 0xd0, 0x3b, 0x46, 0x72, 0x36, 0xb2, 0x61, 0xd3, 0xac, 0x2f,
	0xdf, 0xfb, 0xbf, 0x41, 0xd7, 0x1c, 0x7e, 0x0a, 0xc9, 0x31, 0x12, 0xeb, 0x37, 0x67, 0x27, 0x47,
	0x7b, 0xf7, 0x9a, 0x70, 0x6d, 0x65, 0x5e, 0x40, 0x72, 0x28, 0x25, 0xdb, 0xf4, 0x6f, 0xf9, 0xc1,
	0x9a, 0x7d, 0x13, 0xe8, 0x86, 0x2d, 0xbe, 0xed, 0x9b, 0xb5, 0x3d, 0x7f, 0x06, 0xdd, 0x70, 0x93,
	0x6e, 0x16, 0xb4, 0x7a, 0xc7, 0x5e, 0xf7, 0x3e, 0x86, 0x87, 0xfd, 0x53, 0xd7, 0x3f, 0xf3, 0xaf,
	0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x69, 0x7a, 0x6a, 0x54, 0xfb, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlaceStoreServiceClient is the client API for PlaceStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlaceStoreServiceClient interface {
	GetList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListResponse, error)
	Get(ctx context.Context, in *ID, opts ...grpc.CallOption) (*DetailResponse, error)
	Add(ctx context.Context, in *PlaceStore, opts ...grpc.CallOption) (*CreateResponse, error)
	Update(ctx context.Context, in *PlaceStore, opts ...grpc.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *ID, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type placeStoreServiceClient struct {
	cc *grpc.ClientConn
}

func NewPlaceStoreServiceClient(cc *grpc.ClientConn) PlaceStoreServiceClient {
	return &placeStoreServiceClient{cc}
}

func (c *placeStoreServiceClient) GetList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/place.PlaceStoreService/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placeStoreServiceClient) Get(ctx context.Context, in *ID, opts ...grpc.CallOption) (*DetailResponse, error) {
	out := new(DetailResponse)
	err := c.cc.Invoke(ctx, "/place.PlaceStoreService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placeStoreServiceClient) Add(ctx context.Context, in *PlaceStore, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/place.PlaceStoreService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placeStoreServiceClient) Update(ctx context.Context, in *PlaceStore, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/place.PlaceStoreService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placeStoreServiceClient) Delete(ctx context.Context, in *ID, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/place.PlaceStoreService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaceStoreServiceServer is the server API for PlaceStoreService service.
type PlaceStoreServiceServer interface {
	GetList(context.Context, *Empty) (*ListResponse, error)
	Get(context.Context, *ID) (*DetailResponse, error)
	Add(context.Context, *PlaceStore) (*CreateResponse, error)
	Update(context.Context, *PlaceStore) (*UpdateResponse, error)
	Delete(context.Context, *ID) (*DeleteResponse, error)
}

// UnimplementedPlaceStoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPlaceStoreServiceServer struct {
}

func (*UnimplementedPlaceStoreServiceServer) GetList(ctx context.Context, req *Empty) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (*UnimplementedPlaceStoreServiceServer) Get(ctx context.Context, req *ID) (*DetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedPlaceStoreServiceServer) Add(ctx context.Context, req *PlaceStore) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedPlaceStoreServiceServer) Update(ctx context.Context, req *PlaceStore) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedPlaceStoreServiceServer) Delete(ctx context.Context, req *ID) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterPlaceStoreServiceServer(s *grpc.Server, srv PlaceStoreServiceServer) {
	s.RegisterService(&_PlaceStoreService_serviceDesc, srv)
}

func _PlaceStoreService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaceStoreServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/place.PlaceStoreService/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaceStoreServiceServer).GetList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaceStoreService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaceStoreServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/place.PlaceStoreService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaceStoreServiceServer).Get(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaceStoreService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceStore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaceStoreServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/place.PlaceStoreService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaceStoreServiceServer).Add(ctx, req.(*PlaceStore))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaceStoreService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceStore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaceStoreServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/place.PlaceStoreService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaceStoreServiceServer).Update(ctx, req.(*PlaceStore))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaceStoreService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaceStoreServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/place.PlaceStoreService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaceStoreServiceServer).Delete(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlaceStoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "place.PlaceStoreService",
	HandlerType: (*PlaceStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _PlaceStoreService_GetList_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _PlaceStoreService_Get_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _PlaceStoreService_Add_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PlaceStoreService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PlaceStoreService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "place.store.proto",
}
