// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package product

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestEmpty) Reset()         { *m = RequestEmpty{} }
func (m *RequestEmpty) String() string { return proto.CompactTextString(m) }
func (*RequestEmpty) ProtoMessage()    {}
func (*RequestEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

func (m *RequestEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestEmpty.Unmarshal(m, b)
}
func (m *RequestEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestEmpty.Marshal(b, m, deterministic)
}
func (m *RequestEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestEmpty.Merge(m, src)
}
func (m *RequestEmpty) XXX_Size() int {
	return xxx_messageInfo_RequestEmpty.Size(m)
}
func (m *RequestEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_RequestEmpty proto.InternalMessageInfo

type Coordinate struct {
	Lon                  float32  `protobuf:"fixed32,1,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat                  float32  `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{1}
}

func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (m *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(m, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *Coordinate) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

type Accompaniment struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Accompaniment) Reset()         { *m = Accompaniment{} }
func (m *Accompaniment) String() string { return proto.CompactTextString(m) }
func (*Accompaniment) ProtoMessage()    {}
func (*Accompaniment) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{2}
}

func (m *Accompaniment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Accompaniment.Unmarshal(m, b)
}
func (m *Accompaniment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Accompaniment.Marshal(b, m, deterministic)
}
func (m *Accompaniment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Accompaniment.Merge(m, src)
}
func (m *Accompaniment) XXX_Size() int {
	return xxx_messageInfo_Accompaniment.Size(m)
}
func (m *Accompaniment) XXX_DiscardUnknown() {
	xxx_messageInfo_Accompaniment.DiscardUnknown(m)
}

var xxx_messageInfo_Accompaniment proto.InternalMessageInfo

func (m *Accompaniment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Picture struct {
	Src                  string   `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Picture) Reset()         { *m = Picture{} }
func (m *Picture) String() string { return proto.CompactTextString(m) }
func (*Picture) ProtoMessage()    {}
func (*Picture) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{3}
}

func (m *Picture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Picture.Unmarshal(m, b)
}
func (m *Picture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Picture.Marshal(b, m, deterministic)
}
func (m *Picture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Picture.Merge(m, src)
}
func (m *Picture) XXX_Size() int {
	return xxx_messageInfo_Picture.Size(m)
}
func (m *Picture) XXX_DiscardUnknown() {
	xxx_messageInfo_Picture.DiscardUnknown(m)
}

var xxx_messageInfo_Picture proto.InternalMessageInfo

func (m *Picture) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

type Gallery struct {
	Main                 int32      `protobuf:"varint,1,opt,name=main,proto3" json:"main,omitempty"`
	Pictures             []*Picture `protobuf:"bytes,2,rep,name=pictures,proto3" json:"pictures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Gallery) Reset()         { *m = Gallery{} }
func (m *Gallery) String() string { return proto.CompactTextString(m) }
func (*Gallery) ProtoMessage()    {}
func (*Gallery) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{4}
}

func (m *Gallery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gallery.Unmarshal(m, b)
}
func (m *Gallery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gallery.Marshal(b, m, deterministic)
}
func (m *Gallery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gallery.Merge(m, src)
}
func (m *Gallery) XXX_Size() int {
	return xxx_messageInfo_Gallery.Size(m)
}
func (m *Gallery) XXX_DiscardUnknown() {
	xxx_messageInfo_Gallery.DiscardUnknown(m)
}

var xxx_messageInfo_Gallery proto.InternalMessageInfo

func (m *Gallery) GetMain() int32 {
	if m != nil {
		return m.Main
	}
	return 0
}

func (m *Gallery) GetPictures() []*Picture {
	if m != nil {
		return m.Pictures
	}
	return nil
}

type Category struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{5}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Location struct {
	Address              string      `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Cpc                  string      `protobuf:"bytes,2,opt,name=cpc,proto3" json:"cpc,omitempty"`
	Zone                 string      `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	Location             *Coordinate `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{6}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Location) GetCpc() string {
	if m != nil {
		return m.Cpc
	}
	return ""
}

func (m *Location) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *Location) GetLocation() *Coordinate {
	if m != nil {
		return m.Location
	}
	return nil
}

type Schedule struct {
	Date                 string   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	StartAm              string   `protobuf:"bytes,2,opt,name=start_am,json=startAm,proto3" json:"start_am,omitempty"`
	EndAm                string   `protobuf:"bytes,3,opt,name=end_am,json=endAm,proto3" json:"end_am,omitempty"`
	StartPm              string   `protobuf:"bytes,4,opt,name=start_pm,json=startPm,proto3" json:"start_pm,omitempty"`
	EndPm                string   `protobuf:"bytes,5,opt,name=end_pm,json=endPm,proto3" json:"end_pm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Schedule) Reset()         { *m = Schedule{} }
func (m *Schedule) String() string { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()    {}
func (*Schedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{7}
}

func (m *Schedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schedule.Unmarshal(m, b)
}
func (m *Schedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schedule.Marshal(b, m, deterministic)
}
func (m *Schedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schedule.Merge(m, src)
}
func (m *Schedule) XXX_Size() int {
	return xxx_messageInfo_Schedule.Size(m)
}
func (m *Schedule) XXX_DiscardUnknown() {
	xxx_messageInfo_Schedule.DiscardUnknown(m)
}

var xxx_messageInfo_Schedule proto.InternalMessageInfo

func (m *Schedule) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Schedule) GetStartAm() string {
	if m != nil {
		return m.StartAm
	}
	return ""
}

func (m *Schedule) GetEndAm() string {
	if m != nil {
		return m.EndAm
	}
	return ""
}

func (m *Schedule) GetStartPm() string {
	if m != nil {
		return m.StartPm
	}
	return ""
}

func (m *Schedule) GetEndPm() string {
	if m != nil {
		return m.EndPm
	}
	return ""
}

type Recipes struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Quantity             float32  `protobuf:"fixed32,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Recipes) Reset()         { *m = Recipes{} }
func (m *Recipes) String() string { return proto.CompactTextString(m) }
func (*Recipes) ProtoMessage()    {}
func (*Recipes) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{8}
}

func (m *Recipes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recipes.Unmarshal(m, b)
}
func (m *Recipes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recipes.Marshal(b, m, deterministic)
}
func (m *Recipes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recipes.Merge(m, src)
}
func (m *Recipes) XXX_Size() int {
	return xxx_messageInfo_Recipes.Size(m)
}
func (m *Recipes) XXX_DiscardUnknown() {
	xxx_messageInfo_Recipes.DiscardUnknown(m)
}

var xxx_messageInfo_Recipes proto.InternalMessageInfo

func (m *Recipes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Recipes) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type Product struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category             string      `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Gastronomies         []string    `protobuf:"bytes,4,rep,name=gastronomies,proto3" json:"gastronomies,omitempty"`
	Description          string      `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Recipes              *Recipes    `protobuf:"bytes,6,opt,name=recipes,proto3" json:"recipes,omitempty"`
	Spicy                int32       `protobuf:"varint,7,opt,name=spicy,proto3" json:"spicy,omitempty"`
	Price                int32       `protobuf:"varint,8,opt,name=price,proto3" json:"price,omitempty"`
	Discount             float32     `protobuf:"fixed32,9,opt,name=discount,proto3" json:"discount,omitempty"`
	Quantity             int32       `protobuf:"varint,10,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Size                 string      `protobuf:"bytes,11,opt,name=size,proto3" json:"size,omitempty"`
	Notation             int32       `protobuf:"varint,12,opt,name=notation,proto3" json:"notation,omitempty"`
	Likes                int64       `protobuf:"varint,13,opt,name=likes,proto3" json:"likes,omitempty"`
	Placeid              string      `protobuf:"bytes,14,opt,name=placeid,proto3" json:"placeid,omitempty"`
	Placename            string      `protobuf:"bytes,15,opt,name=placename,proto3" json:"placename,omitempty"`
	Placelogo            string      `protobuf:"bytes,16,opt,name=placelogo,proto3" json:"placelogo,omitempty"`
	Placezone            string      `protobuf:"bytes,17,opt,name=placezone,proto3" json:"placezone,omitempty"`
	Location             *Coordinate `protobuf:"bytes,18,opt,name=location,proto3" json:"location,omitempty"`
	Picture              *Picture    `protobuf:"bytes,19,opt,name=picture,proto3" json:"picture,omitempty"`
	MenuAvailable        bool        `protobuf:"varint,20,opt,name=menu_available,json=menuAvailable,proto3" json:"menu_available,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{9}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Product) GetGastronomies() []string {
	if m != nil {
		return m.Gastronomies
	}
	return nil
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetRecipes() *Recipes {
	if m != nil {
		return m.Recipes
	}
	return nil
}

func (m *Product) GetSpicy() int32 {
	if m != nil {
		return m.Spicy
	}
	return 0
}

func (m *Product) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetDiscount() float32 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *Product) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Product) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *Product) GetNotation() int32 {
	if m != nil {
		return m.Notation
	}
	return 0
}

func (m *Product) GetLikes() int64 {
	if m != nil {
		return m.Likes
	}
	return 0
}

func (m *Product) GetPlaceid() string {
	if m != nil {
		return m.Placeid
	}
	return ""
}

func (m *Product) GetPlacename() string {
	if m != nil {
		return m.Placename
	}
	return ""
}

func (m *Product) GetPlacelogo() string {
	if m != nil {
		return m.Placelogo
	}
	return ""
}

func (m *Product) GetPlacezone() string {
	if m != nil {
		return m.Placezone
	}
	return ""
}

func (m *Product) GetLocation() *Coordinate {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Product) GetPicture() *Picture {
	if m != nil {
		return m.Picture
	}
	return nil
}

func (m *Product) GetMenuAvailable() bool {
	if m != nil {
		return m.MenuAvailable
	}
	return false
}

type ListResponse struct {
	Status               int32      `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Total                int64      `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Payload              []*Product `protobuf:"bytes,4,rep,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{10}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ListResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListResponse) GetPayload() []*Product {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateRequest struct {
	Payload              *Product `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{11}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetPayload() *Product {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Payload              bool     `protobuf:"varint,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{12}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateResponse) GetPayload() bool {
	if m != nil {
		return m.Payload
	}
	return false
}

type DetailRequest struct {
	Id                   string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailRequest) Reset()         { *m = DetailRequest{} }
func (m *DetailRequest) String() string { return proto.CompactTextString(m) }
func (*DetailRequest) ProtoMessage()    {}
func (*DetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{13}
}

func (m *DetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailRequest.Unmarshal(m, b)
}
func (m *DetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailRequest.Marshal(b, m, deterministic)
}
func (m *DetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailRequest.Merge(m, src)
}
func (m *DetailRequest) XXX_Size() int {
	return xxx_messageInfo_DetailRequest.Size(m)
}
func (m *DetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetailRequest proto.InternalMessageInfo

func (m *DetailRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DetailResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Payload              *Product `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailResponse) Reset()         { *m = DetailResponse{} }
func (m *DetailResponse) String() string { return proto.CompactTextString(m) }
func (*DetailResponse) ProtoMessage()    {}
func (*DetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{14}
}

func (m *DetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailResponse.Unmarshal(m, b)
}
func (m *DetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailResponse.Marshal(b, m, deterministic)
}
func (m *DetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailResponse.Merge(m, src)
}
func (m *DetailResponse) XXX_Size() int {
	return xxx_messageInfo_DetailResponse.Size(m)
}
func (m *DetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetailResponse proto.InternalMessageInfo

func (m *DetailResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DetailResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DetailResponse) GetPayload() *Product {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload              *Product `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{15}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetPayload() *Product {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Payload              bool     `protobuf:"varint,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{16}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UpdateResponse) GetPayload() bool {
	if m != nil {
		return m.Payload
	}
	return false
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{17}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Payload              bool     `protobuf:"varint,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{18}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DeleteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DeleteResponse) GetPayload() bool {
	if m != nil {
		return m.Payload
	}
	return false
}

type SearchParams struct {
	Q                    string   `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	From                 int32    `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   int32    `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	Fromdate             string   `protobuf:"bytes,4,opt,name=fromdate,proto3" json:"fromdate,omitempty"`
	Todate               string   `protobuf:"bytes,5,opt,name=todate,proto3" json:"todate,omitempty"`
	Category             []string `protobuf:"bytes,6,rep,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchParams) Reset()         { *m = SearchParams{} }
func (m *SearchParams) String() string { return proto.CompactTextString(m) }
func (*SearchParams) ProtoMessage()    {}
func (*SearchParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{19}
}

func (m *SearchParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchParams.Unmarshal(m, b)
}
func (m *SearchParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchParams.Marshal(b, m, deterministic)
}
func (m *SearchParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchParams.Merge(m, src)
}
func (m *SearchParams) XXX_Size() int {
	return xxx_messageInfo_SearchParams.Size(m)
}
func (m *SearchParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchParams.DiscardUnknown(m)
}

var xxx_messageInfo_SearchParams proto.InternalMessageInfo

func (m *SearchParams) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *SearchParams) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *SearchParams) GetTo() int32 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *SearchParams) GetFromdate() string {
	if m != nil {
		return m.Fromdate
	}
	return ""
}

func (m *SearchParams) GetTodate() string {
	if m != nil {
		return m.Todate
	}
	return ""
}

func (m *SearchParams) GetCategory() []string {
	if m != nil {
		return m.Category
	}
	return nil
}

func init() {
	proto.RegisterType((*RequestEmpty)(nil), "product.RequestEmpty")
	proto.RegisterType((*Coordinate)(nil), "product.Coordinate")
	proto.RegisterType((*Accompaniment)(nil), "product.Accompaniment")
	proto.RegisterType((*Picture)(nil), "product.Picture")
	proto.RegisterType((*Gallery)(nil), "product.Gallery")
	proto.RegisterType((*Category)(nil), "product.Category")
	proto.RegisterType((*Location)(nil), "product.Location")
	proto.RegisterType((*Schedule)(nil), "product.Schedule")
	proto.RegisterType((*Recipes)(nil), "product.Recipes")
	proto.RegisterType((*Product)(nil), "product.Product")
	proto.RegisterType((*ListResponse)(nil), "product.ListResponse")
	proto.RegisterType((*CreateRequest)(nil), "product.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "product.CreateResponse")
	proto.RegisterType((*DetailRequest)(nil), "product.DetailRequest")
	proto.RegisterType((*DetailResponse)(nil), "product.DetailResponse")
	proto.RegisterType((*UpdateRequest)(nil), "product.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "product.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "product.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "product.DeleteResponse")
	proto.RegisterType((*SearchParams)(nil), "product.SearchParams")
}

func init() { proto.RegisterFile("product.proto", fileDescriptor_f0fd8b59378f44a5) }

var fileDescriptor_f0fd8b59378f44a5 = []byte{
	// 971 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xef, 0x8a, 0x1c, 0x45,
	0x10, 0x67, 0x66, 0x6e, 0xff, 0xd5, 0xed, 0xae, 0xb1, 0x2f, 0x89, 0xed, 0x29, 0xba, 0x8c, 0x08,
	0x4b, 0x90, 0x28, 0x27, 0x04, 0x0e, 0x15, 0xb2, 0x9e, 0xe1, 0x3e, 0x24, 0x1f, 0x8e, 0x39, 0x84,
	0xe0, 0x97, 0xd0, 0x99, 0x6e, 0x2f, 0xad, 0x33, 0xd3, 0x73, 0xdd, 0xbd, 0x81, 0x8d, 0xe0, 0x07,
	0x9f, 0xc0, 0x27, 0xf1, 0x51, 0x7c, 0x03, 0xdf, 0x45, 0xfa, 0xef, 0xce, 0xec, 0x0a, 0xb9, 0x1c,
	0x7e, 0xda, 0xaa, 0xea, 0xaa, 0xea, 0x5f, 0xfd, 0xba, 0xaa, 0x76, 0x60, 0xd6, 0x4a, 0x41, 0xd7,
	0xa5, 0x7e, 0xd8, 0x4a, 0xa1, 0x05, 0x1a, 0x79, 0x35, 0x9f, 0xc3, 0xb4, 0x60, 0xd7, 0x6b, 0xa6,
	0xf4, 0x93, 0xba, 0xd5, 0x9b, 0xfc, 0x2b, 0x80, 0x33, 0x21, 0x24, 0xe5, 0x0d, 0xd1, 0x0c, 0xdd,
	0x81, 0xac, 0x12, 0x0d, 0x4e, 0x16, 0xc9, 0x32, 0x2d, 0x8c, 0x68, 0x2d, 0x44, 0xe3, 0xd4, 0x5b,
	0x88, 0xce, 0x3f, 0x83, 0xd9, 0xaa, 0x2c, 0x45, 0xdd, 0x92, 0x86, 0xd7, 0xac, 0xd1, 0x08, 0xc1,
	0x41, 0x43, 0x6a, 0x66, 0xa3, 0x26, 0x85, 0x95, 0xf3, 0x8f, 0x60, 0x74, 0xc1, 0x4b, 0xbd, 0x96,
	0x36, 0xa7, 0x92, 0xa5, 0x3f, 0x35, 0x62, 0xfe, 0x14, 0x46, 0xe7, 0xa4, 0xaa, 0x98, 0xdc, 0x98,
	0xd8, 0x9a, 0x70, 0x77, 0xe3, 0xa0, 0xb0, 0x32, 0xfa, 0x02, 0xc6, 0xad, 0x8b, 0x55, 0x38, 0x5d,
	0x64, 0xcb, 0xc3, 0x93, 0x3b, 0x0f, 0x43, 0x35, 0x3e, 0x69, 0x11, 0x3d, 0xf2, 0x4f, 0x60, 0x7c,
	0x46, 0x34, 0xbb, 0x12, 0x2e, 0xdb, 0x1e, 0x92, 0xdf, 0x60, 0xfc, 0x4c, 0x94, 0x44, 0x73, 0xd1,
	0x20, 0x0c, 0x23, 0x42, 0xa9, 0x64, 0x4a, 0x79, 0x97, 0xa0, 0x1a, 0x90, 0x65, 0x5b, 0xda, 0x32,
	0x27, 0x85, 0x11, 0x4d, 0xae, 0x37, 0xa2, 0x61, 0x38, 0x73, 0xb9, 0x8c, 0x8c, 0xbe, 0x84, 0x71,
	0xe5, 0x73, 0xe1, 0x83, 0x45, 0xb2, 0x3c, 0x3c, 0x39, 0x8a, 0xc8, 0xb6, 0x2c, 0x16, 0xd1, 0x29,
	0xff, 0x23, 0x81, 0xf1, 0x65, 0xf9, 0x8a, 0xd1, 0x75, 0xc5, 0x4c, 0x46, 0x4a, 0x74, 0x44, 0x67,
	0x64, 0xf4, 0x21, 0x8c, 0x95, 0x26, 0x52, 0xbf, 0x20, 0xb5, 0xbf, 0x7c, 0x64, 0xf5, 0x55, 0x8d,
	0xee, 0xc1, 0x90, 0x35, 0xd4, 0x1c, 0x38, 0x08, 0x03, 0xd6, 0xd0, 0x55, 0xbd, 0x8d, 0x68, 0x6b,
	0x8b, 0x21, 0x44, 0x5c, 0xc4, 0x88, 0xb6, 0xc6, 0x83, 0x18, 0x71, 0x51, 0xe7, 0xa7, 0x30, 0x2a,
	0x58, 0xc9, 0x5b, 0xa6, 0xfe, 0x8b, 0x20, 0x74, 0x0c, 0xe3, 0xeb, 0x35, 0x69, 0x34, 0xd7, 0x1b,
	0xff, 0xcc, 0x51, 0xcf, 0xff, 0x39, 0x80, 0xd1, 0x85, 0x2b, 0x10, 0xcd, 0x21, 0xe5, 0xd4, 0x47,
	0xa6, 0x9c, 0xc6, 0x5c, 0x69, 0x3f, 0x57, 0xe9, 0x1f, 0xc3, 0xa3, 0x8e, 0x3a, 0xca, 0x61, 0x7a,
	0x45, 0x94, 0x96, 0xa2, 0x11, 0x35, 0x67, 0x0a, 0x1f, 0x2c, 0xb2, 0xe5, 0xa4, 0xe8, 0xd9, 0xd0,
	0x02, 0x0e, 0x29, 0x53, 0xa5, 0xe4, 0xad, 0xe5, 0xd8, 0x95, 0xd1, 0x35, 0xa1, 0x07, 0x30, 0x92,
	0xae, 0x18, 0x3c, 0xb4, 0x2f, 0xb0, 0xed, 0x0d, 0x5f, 0x64, 0x11, 0x1c, 0xd0, 0x5d, 0x18, 0xa8,
	0x96, 0x97, 0x1b, 0x3c, 0xb2, 0xdd, 0xe5, 0x14, 0x63, 0x6d, 0x25, 0x2f, 0x19, 0x1e, 0x3b, 0xab,
	0x55, 0x0c, 0x72, 0xca, 0x55, 0x29, 0xd6, 0x8d, 0xc6, 0x13, 0xc7, 0x42, 0xd0, 0x7b, 0x0c, 0x81,
	0x0d, 0x8a, 0xba, 0x61, 0x41, 0xf1, 0x37, 0x0c, 0x1f, 0x3a, 0x16, 0x8c, 0x6c, 0xfc, 0x1b, 0xa1,
	0x5d, 0x9b, 0x4c, 0x9d, 0x7f, 0xd0, 0xcd, 0xed, 0x15, 0xff, 0x95, 0x29, 0x3c, 0x5b, 0x24, 0xcb,
	0xac, 0x70, 0x8a, 0x69, 0xcc, 0xb6, 0x22, 0x25, 0xe3, 0x14, 0xcf, 0xdd, 0x9b, 0x7a, 0x15, 0x7d,
	0x0c, 0x13, 0x2b, 0x5a, 0xaa, 0xdf, 0xb3, 0x67, 0x5b, 0x43, 0x3c, 0xad, 0xc4, 0x95, 0xc0, 0x77,
	0x3a, 0xa7, 0xc6, 0x10, 0x4f, 0x6d, 0x1f, 0xbf, 0xdf, 0x39, 0xdd, 0x6b, 0x66, 0x74, 0x83, 0x66,
	0x36, 0xd4, 0xfb, 0xa9, 0xc3, 0x47, 0x3b, 0xd4, 0x87, 0xb1, 0x0c, 0x0e, 0xe8, 0x73, 0x98, 0xd7,
	0xac, 0x59, 0xbf, 0x20, 0xaf, 0x09, 0xaf, 0xc8, 0xcb, 0x8a, 0xe1, 0xbb, 0x8b, 0x64, 0x39, 0x2e,
	0x66, 0xc6, 0xba, 0x0a, 0xc6, 0xfc, 0x77, 0x98, 0x3e, 0xe3, 0x4a, 0x17, 0x4c, 0xb5, 0xa2, 0x51,
	0x0c, 0xdd, 0x87, 0xa1, 0xd2, 0x44, 0xaf, 0x95, 0x5f, 0x08, 0x5e, 0x33, 0xac, 0x31, 0x29, 0x85,
	0xf4, 0xcd, 0xe6, 0x14, 0x63, 0xd5, 0x42, 0x93, 0xca, 0xb6, 0x5a, 0x56, 0x38, 0xc5, 0xc2, 0x24,
	0x9b, 0x4a, 0x10, 0x6a, 0x5b, 0xac, 0x07, 0xd3, 0xfd, 0x16, 0xc1, 0x21, 0xff, 0x06, 0x66, 0x67,
	0x92, 0x99, 0x32, 0xdd, 0x4e, 0xec, 0x06, 0x27, 0xbb, 0x35, 0xee, 0x06, 0x3f, 0x87, 0x79, 0x08,
	0xbe, 0x29, 0xfc, 0xac, 0x0b, 0x1f, 0x6f, 0xef, 0x4a, 0x2d, 0x39, 0x31, 0xf3, 0xa7, 0x30, 0xfb,
	0x81, 0x69, 0xc2, 0xab, 0x00, 0xcb, 0xcd, 0xde, 0x41, 0x98, 0xbd, 0xfc, 0x17, 0x98, 0x07, 0x87,
	0x5b, 0x31, 0xd7, 0x29, 0x33, 0x7b, 0x5b, 0x99, 0x4f, 0x61, 0xf6, 0x63, 0x4b, 0x3b, 0x1c, 0xed,
	0x2e, 0x82, 0x07, 0xfd, 0x3a, 0xde, 0xc6, 0x59, 0x48, 0x76, 0x2b, 0xe0, 0xb8, 0x0f, 0x7c, 0x97,
	0xb3, 0x8a, 0xed, 0xc2, 0xcc, 0x22, 0x67, 0xcf, 0x0d, 0x67, 0xce, 0xe1, 0x7f, 0xbe, 0xfa, 0xcf,
	0x04, 0xa6, 0x97, 0x8c, 0xc8, 0xf2, 0xd5, 0x05, 0x91, 0xa4, 0x56, 0x68, 0x0a, 0xc9, 0xb5, 0x27,
	0x28, 0xb9, 0x36, 0x2b, 0xe2, 0x67, 0x29, 0xdc, 0x7e, 0x1f, 0x14, 0x56, 0x36, 0xe0, 0xb4, 0xb0,
	0x79, 0x06, 0x45, 0xaa, 0x85, 0x59, 0x19, 0xc6, 0x6e, 0xff, 0x1f, 0xdc, 0x33, 0x47, 0xdd, 0xc0,
	0xd4, 0xc2, 0x9e, 0xb8, 0x7d, 0xe8, 0xb5, 0xde, 0xb2, 0x1d, 0xda, 0x65, 0x1a, 0xf5, 0x93, 0xbf,
	0x52, 0x98, 0x7b, 0xf2, 0x2f, 0x99, 0x7c, 0x6d, 0x36, 0xdc, 0x23, 0x18, 0x3a, 0x90, 0xe8, 0x5e,
	0x7c, 0x9f, 0x2e, 0xea, 0xe3, 0xad, 0xb9, 0x37, 0x93, 0x8f, 0x20, 0x3b, 0x67, 0x1a, 0xdd, 0x8f,
	0xa7, 0xbd, 0xd6, 0x3c, 0xfe, 0x60, 0xcf, 0xbe, 0x8d, 0x5b, 0x51, 0xda, 0x89, 0xeb, 0x4d, 0x5a,
	0x27, 0x6e, 0x67, 0x88, 0x4e, 0x61, 0xe8, 0x5a, 0xa4, 0x13, 0xda, 0x6b, 0xc0, 0x4e, 0xe8, 0x4e,
	0x2f, 0x9d, 0xc2, 0xd0, 0x3d, 0x71, 0x0f, 0x6d, 0xa7, 0x29, 0x7a, 0x68, 0xbb, 0xbd, 0x70, 0xf2,
	0x77, 0x0a, 0x47, 0x91, 0x30, 0x43, 0xca, 0x93, 0xe6, 0x8a, 0x37, 0xb7, 0x67, 0xed, 0x5b, 0x98,
	0x9c, 0x33, 0xed, 0x28, 0x79, 0x77, 0xee, 0xbe, 0x03, 0x58, 0x51, 0x1a, 0xfe, 0x79, 0xdf, 0x99,
	0xc2, 0xc7, 0x61, 0x64, 0xf7, 0x33, 0xdc, 0x90, 0xc9, 0xc7, 0x61, 0x9a, 0xf6, 0x33, 0xdc, 0x8c,
	0xd0, 0xef, 0x27, 0x3f, 0x85, 0x6f, 0xce, 0x97, 0x43, 0xfb, 0x0d, 0xfa, 0xf5, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x47, 0xc5, 0x8a, 0xaf, 0x94, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	Search(ctx context.Context, in *SearchParams, opts ...grpc.CallOption) (*ListResponse, error)
	Get(ctx context.Context, in *DetailRequest, opts ...grpc.CallOption) (*DetailResponse, error)
	Add(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type productServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductServiceClient(cc *grpc.ClientConn) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) Search(ctx context.Context, in *SearchParams, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) Get(ctx context.Context, in *DetailRequest, opts ...grpc.CallOption) (*DetailResponse, error) {
	out := new(DetailResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) Add(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	Search(context.Context, *SearchParams) (*ListResponse, error)
	Get(context.Context, *DetailRequest) (*DetailResponse, error)
	Add(context.Context, *CreateRequest) (*CreateResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

// UnimplementedProductServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (*UnimplementedProductServiceServer) Search(ctx context.Context, req *SearchParams) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedProductServiceServer) Get(ctx context.Context, req *DetailRequest) (*DetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedProductServiceServer) Add(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedProductServiceServer) Update(ctx context.Context, req *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedProductServiceServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).Search(ctx, req.(*SearchParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).Get(ctx, req.(*DetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).Add(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _ProductService_Search_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ProductService_Get_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _ProductService_Add_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProductService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ProductService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}

// ProductSearchEngineClient is the client API for ProductSearchEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductSearchEngineClient interface {
	Search(ctx context.Context, in *SearchParams, opts ...grpc.CallOption) (*ListResponse, error)
	GetDetail(ctx context.Context, in *DetailRequest, opts ...grpc.CallOption) (*DetailResponse, error)
	AddProduct(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	UpdateProduct(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	DeleteProduct(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type productSearchEngineClient struct {
	cc *grpc.ClientConn
}

func NewProductSearchEngineClient(cc *grpc.ClientConn) ProductSearchEngineClient {
	return &productSearchEngineClient{cc}
}

func (c *productSearchEngineClient) Search(ctx context.Context, in *SearchParams, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/product.ProductSearchEngine/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productSearchEngineClient) GetDetail(ctx context.Context, in *DetailRequest, opts ...grpc.CallOption) (*DetailResponse, error) {
	out := new(DetailResponse)
	err := c.cc.Invoke(ctx, "/product.ProductSearchEngine/GetDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productSearchEngineClient) AddProduct(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/product.ProductSearchEngine/AddProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productSearchEngineClient) UpdateProduct(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/product.ProductSearchEngine/UpdateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productSearchEngineClient) DeleteProduct(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/product.ProductSearchEngine/DeleteProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductSearchEngineServer is the server API for ProductSearchEngine service.
type ProductSearchEngineServer interface {
	Search(context.Context, *SearchParams) (*ListResponse, error)
	GetDetail(context.Context, *DetailRequest) (*DetailResponse, error)
	AddProduct(context.Context, *CreateRequest) (*CreateResponse, error)
	UpdateProduct(context.Context, *UpdateRequest) (*UpdateResponse, error)
	DeleteProduct(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

// UnimplementedProductSearchEngineServer can be embedded to have forward compatible implementations.
type UnimplementedProductSearchEngineServer struct {
}

func (*UnimplementedProductSearchEngineServer) Search(ctx context.Context, req *SearchParams) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedProductSearchEngineServer) GetDetail(ctx context.Context, req *DetailRequest) (*DetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDetail not implemented")
}
func (*UnimplementedProductSearchEngineServer) AddProduct(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProduct not implemented")
}
func (*UnimplementedProductSearchEngineServer) UpdateProduct(ctx context.Context, req *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (*UnimplementedProductSearchEngineServer) DeleteProduct(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProduct not implemented")
}

func RegisterProductSearchEngineServer(s *grpc.Server, srv ProductSearchEngineServer) {
	s.RegisterService(&_ProductSearchEngine_serviceDesc, srv)
}

func _ProductSearchEngine_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductSearchEngineServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductSearchEngine/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductSearchEngineServer).Search(ctx, req.(*SearchParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductSearchEngine_GetDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductSearchEngineServer).GetDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductSearchEngine/GetDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductSearchEngineServer).GetDetail(ctx, req.(*DetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductSearchEngine_AddProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductSearchEngineServer).AddProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductSearchEngine/AddProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductSearchEngineServer).AddProduct(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductSearchEngine_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductSearchEngineServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductSearchEngine/UpdateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductSearchEngineServer).UpdateProduct(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductSearchEngine_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductSearchEngineServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductSearchEngine/DeleteProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductSearchEngineServer).DeleteProduct(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductSearchEngine_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductSearchEngine",
	HandlerType: (*ProductSearchEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _ProductSearchEngine_Search_Handler,
		},
		{
			MethodName: "GetDetail",
			Handler:    _ProductSearchEngine_GetDetail_Handler,
		},
		{
			MethodName: "AddProduct",
			Handler:    _ProductSearchEngine_AddProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _ProductSearchEngine_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _ProductSearchEngine_DeleteProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
